// The filters PGSharp saves — which spawns the radar and the nearby feed are looking for. Unlike a control's position,
// which is a Java Float, each of these is stored as one JSON string; they are kept as objects here so every field reads
// and diffs on its own, and JSON.stringify re-emits the compact string PGSharp wrote where they are put in the backup.
// That re-emission goes field by field in source order, so the order below is part of the value and must not be
// rearranged. Every value is taken verbatim from a known-good backup and none is user-editable.

import POKEMON from './pokemon.js';

// A species' dex number, which is what PGSharp stores — the reverse of pokemon.js, built once so a filter's species
// list costs one lookup each. A name the dex has no entry for is a typo rather than a species PGSharp knows, so it
// stops the backup here instead of reaching the file as some other species or as nothing at all.
const DEX_NUMBERS = new Map(POKEMON.map((name, i) => [name, i + 1]));

function dexNumber(name) {
  const number = DEX_NUMBERS.get(name);

  if (!number) {
    throw new Error(`no Pokémon named "${name}" — check the spelling against pokemon.js`);
  }

  return number;
}

// The nearby radar's own filter, stored under "hlscan" — it rides along with the radar button's position rather than
// ticking separately, since the button is what carries it.
export const SCAN_CONFIG = {
  shiny: true,
  minlv: 1,
  maxlv: 36,
  miniv: 0,
  maxiv: 100,
  checkAll: true,
  onlyShiny: true,
  name: 'Nearby Radar',
  birds: true,
  attrMode: 0,
  minatk: 0,
  maxatk: 15,
  mindef: 0,
  maxdef: 15,
  minsta: 0,
  maxsta: 15,
  showShinyOnly: false,
  loadShiny: true,
  notify: true,
  stop: true,
  pgp: true,
};

// The nearby feed's filter list, stored under "hlfeeds" — the named filters the feed matches spawns against, as one
// JSON array. "Shiny Hunting" watches its own list of species for a shiny within 5 km; "100%" watches every species for
// a perfect one within 10 km and is the only one that notifies. That species list keeps the order PGSharp wrote it in,
// which is neither dex nor alphabetical order, so it is left as found rather than tidied.
export const FEED_FILTERS = [
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 0,
    maxIV: 100,
    onlyShiny: true,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: false,
    name: 'Shiny Hunting',
    distance: 5,
    priority: 0,
    pokemons: [
      'Panpour',
      'Pidove',
      'Tranquill',
      'Unfezant',
      'Roggenrola',
      'Boldore',
      'Gigalith',
      'Woobat',
      'Drilbur',
      'Excadrill',
      'Audino',
      'Tympole',
      'Palpitoad',
      'Seismitoad',
      'Sewaddle',
      'Swadloon',
      'Leavanny',
      'Venipede',
      'Whirlipede',
      'Cottonee',
      'Whimsicott',
      'Maractus',
      'Paras',
      'Scraggy',
      'Scrafty',
      'Sigilyph',
      'Yamask',
      'Cofagrigus',
      'Tirtouga',
      'Archen',
      'Trubbish',
      'Garbodor',
      'Zorua',
      'Deerling',
      'Sawsbuck',
      'Karrablast',
      'Slowpoke',
      'Frillish',
      'Jellicent',
      'Joltik',
      'Galvantula',
      'Doduo',
      'Tynamo',
      'Eelektrik',
      'Elgyem',
      'Beheeyem',
      'Axew',
      'Haxorus',
      'Shelmet',
      'Mienfoo',
      'Mienshao',
      'Golett',
      'Rufflet',
      'Braviary',
      'Goldeen',
      'Seaking',
      'Durant',
      'Staryu',
      'Starmie',
      'Fennekin',
      'Snorlax',
      'Froakie',
      'Greninja',
      'Bunnelby',
      'Diggersby',
      'Flabébé',
      'Floette',
      'Florges',
      'Skiddo',
      'Gogoat',
      'Pancham',
      'Furfrou',
      'Espurr',
      'Honedge',
      'Spritzee',
      'Swirlix',
      'Binacle',
      'Skrelp',
      'Clauncher',
      'Clawitzer',
      'Helioptile',
      'Tyrunt',
      'Tyrantrum',
      'Amaura',
      'Hawlucha',
      'Dedenne',
      'Carbink',
      'Goomy',
      'Sliggoo',
      'Klefki',
      'Phantump',
      'Pumpkaboo',
      'Bergmite',
      'Avalugg',
      'Noibat',
      'Noivern',
      'Girafarig',
      'Rowlet',
      'Dartrix',
      'Decidueye',
      'Litten',
      'Torracat',
      'Incineroar',
      'Popplio',
      'Brionne',
      'Pikipek',
      'Trumbeak',
      'Corsola',
      'Remoraid',
      'Grubbin',
      'Charjabug',
      'Oricorio',
      'Cutiefly',
      'Ribombee',
      'Stantler',
      'Morelull',
      'Shiinotic',
      'Bounsweet',
      'Steenee',
      'Tsareena',
      'Oranguru',
      'Passimian',
      'Wimpod',
      'Sandygast',
      'Palossand',
      'Komala',
      'Togedemaru',
      'Bruxish',
      'Jangmo-o',
      'Grookey',
      'Nosepass',
      'Thwackey',
      'Rillaboom',
      'Scorbunny',
      'Raboot',
      'Cinderace',
      'Sobble',
      'Drizzile',
      'Inteleon',
      'Greedent',
      'Rookidee',
      'Corvisquire',
      'Corviknight',
      'Wooloo',
      'Dubwool',
      'Numel',
      'Camerupt',
      'Torkoal',
      'Seviper',
      'Sizzlipede',
      'Centiskorch',
      'Barboach',
      'Whiscash',
      'Corphish',
      'Crawdaunt',
      'Hatenna',
      'Hattrem',
      'Hatterene',
      'Impidimp',
      'Morgrem',
      'Grimmsnarl',
      'Tropius',
      'Chimecho',
      'Relicanth',
      'Sneasler',
      'Sprigatito',
      'Floragato',
      'Meowscarada',
      'Fuecoco',
      'Crocalor',
      'Skeledirge',
      'Quaxly',
      'Quaxwell',
      'Quaquaval',
      'Lechonk',
      'Oinkologne',
      'Nymble',
      'Cranidos',
      'Lokix',
      'Pawmi',
      'Pawmo',
      'Burmy',
      'Fidough',
      'Dachsbun',
      'Smoliv',
      'Dolliv',
      'Pachirisu',
      'Buizel',
      'Arboliva',
      'Floatzel',
      'Cherubi',
      'Cherrim',
      'Shellos',
      'Gastrodon',
      'Charcadet',
      'Ceruledge',
      'Tadbulb',
      'Bellibolt',
      'Toedscool',
      'Wiglett',
      'Wugtrio',
      'Carnivine',
      'Cetitan',
      'Kingambit',
      'Baxcalibur',
      'Purrloin',
      'Liepard',
    ].map(dexNumber),
  },
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 100,
    maxIV: 100,
    onlyShiny: false,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: true,
    name: '100%',
    distance: 10,
    priority: 0,
  },
];
