// The filters PGSharp saves — which spawns the radar and the nearby feed are looking for. Unlike a control's position,
// which is a Java Float, each of these is stored as one JSON string; they are kept as objects here so every field reads
// and diffs on its own, and JSON.stringify re-emits the compact string PGSharp wrote where they are put in the backup.
// That re-emission goes field by field in source order, so the order below is part of the value and must not be
// rearranged. Every value is taken verbatim from a known-good backup and none is user-editable.

import POKEMON from './pokemon.js';

// A filter's species list, checked. A constant pokemon.js does not define reads as undefined rather than failing, and
// would reach the backup as a null where a species should be, so it stops here instead. The value is all we are handed
// — the constant's name is gone by then — so the error gives the position to look at.
function species(numbers) {
  const at = numbers.findIndex((n) => !Number.isInteger(n));

  if (at !== -1) {
    throw new Error(`species #${at + 1} is not a POKEMON constant — check it against pokemon.js`);
  }

  return numbers;
}

// The nearby radar's own filter, stored under "hlscan" — it rides along with the radar button's position rather than
// ticking separately, since the button is what carries it.
export const SCAN_CONFIG = {
  shiny: true,
  minlv: 1,
  maxlv: 36,
  miniv: 0,
  maxiv: 100,
  checkAll: true,
  onlyShiny: true,
  name: 'Nearby Radar',
  birds: true,
  attrMode: 0,
  minatk: 0,
  maxatk: 15,
  mindef: 0,
  maxdef: 15,
  minsta: 0,
  maxsta: 15,
  showShinyOnly: false,
  loadShiny: true,
  notify: true,
  stop: true,
  pgp: true,
};

// The nearby feed's filter list, stored under "hlfeeds" — the named filters the feed matches spawns against, as one
// JSON array. "Shiny Hunting" watches its own list of species for a shiny within 5 km; "100%" watches every species for
// a perfect one within 10 km and is the only one that notifies. That species list keeps the order PGSharp wrote it in,
// which is neither dex nor alphabetical order, so it is left as found rather than tidied.
export const FEED_FILTERS = [
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 0,
    maxIV: 100,
    onlyShiny: true,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: false,
    name: 'Shiny Hunting',
    distance: 5,
    priority: 0,
    pokemons: species([
      POKEMON.PANPOUR,
      POKEMON.PIDOVE,
      POKEMON.TRANQUILL,
      POKEMON.UNFEZANT,
      POKEMON.ROGGENROLA,
      POKEMON.BOLDORE,
      POKEMON.GIGALITH,
      POKEMON.WOOBAT,
      POKEMON.DRILBUR,
      POKEMON.EXCADRILL,
      POKEMON.AUDINO,
      POKEMON.TYMPOLE,
      POKEMON.PALPITOAD,
      POKEMON.SEISMITOAD,
      POKEMON.SEWADDLE,
      POKEMON.SWADLOON,
      POKEMON.LEAVANNY,
      POKEMON.VENIPEDE,
      POKEMON.WHIRLIPEDE,
      POKEMON.COTTONEE,
      POKEMON.WHIMSICOTT,
      POKEMON.MARACTUS,
      POKEMON.PARAS,
      POKEMON.SCRAGGY,
      POKEMON.SCRAFTY,
      POKEMON.SIGILYPH,
      POKEMON.YAMASK,
      POKEMON.COFAGRIGUS,
      POKEMON.TIRTOUGA,
      POKEMON.ARCHEN,
      POKEMON.TRUBBISH,
      POKEMON.GARBODOR,
      POKEMON.ZORUA,
      POKEMON.DEERLING,
      POKEMON.SAWSBUCK,
      POKEMON.KARRABLAST,
      POKEMON.SLOWPOKE,
      POKEMON.FRILLISH,
      POKEMON.JELLICENT,
      POKEMON.JOLTIK,
      POKEMON.GALVANTULA,
      POKEMON.DODUO,
      POKEMON.TYNAMO,
      POKEMON.EELEKTRIK,
      POKEMON.ELGYEM,
      POKEMON.BEHEEYEM,
      POKEMON.AXEW,
      POKEMON.HAXORUS,
      POKEMON.SHELMET,
      POKEMON.MIENFOO,
      POKEMON.MIENSHAO,
      POKEMON.GOLETT,
      POKEMON.RUFFLET,
      POKEMON.BRAVIARY,
      POKEMON.GOLDEEN,
      POKEMON.SEAKING,
      POKEMON.DURANT,
      POKEMON.STARYU,
      POKEMON.STARMIE,
      POKEMON.FENNEKIN,
      POKEMON.SNORLAX,
      POKEMON.FROAKIE,
      POKEMON.GRENINJA,
      POKEMON.BUNNELBY,
      POKEMON.DIGGERSBY,
      POKEMON.FLABEBE,
      POKEMON.FLOETTE,
      POKEMON.FLORGES,
      POKEMON.SKIDDO,
      POKEMON.GOGOAT,
      POKEMON.PANCHAM,
      POKEMON.FURFROU,
      POKEMON.ESPURR,
      POKEMON.HONEDGE,
      POKEMON.SPRITZEE,
      POKEMON.SWIRLIX,
      POKEMON.BINACLE,
      POKEMON.SKRELP,
      POKEMON.CLAUNCHER,
      POKEMON.CLAWITZER,
      POKEMON.HELIOPTILE,
      POKEMON.TYRUNT,
      POKEMON.TYRANTRUM,
      POKEMON.AMAURA,
      POKEMON.HAWLUCHA,
      POKEMON.DEDENNE,
      POKEMON.CARBINK,
      POKEMON.GOOMY,
      POKEMON.SLIGGOO,
      POKEMON.KLEFKI,
      POKEMON.PHANTUMP,
      POKEMON.PUMPKABOO,
      POKEMON.BERGMITE,
      POKEMON.AVALUGG,
      POKEMON.NOIBAT,
      POKEMON.NOIVERN,
      POKEMON.GIRAFARIG,
      POKEMON.ROWLET,
      POKEMON.DARTRIX,
      POKEMON.DECIDUEYE,
      POKEMON.LITTEN,
      POKEMON.TORRACAT,
      POKEMON.INCINEROAR,
      POKEMON.POPPLIO,
      POKEMON.BRIONNE,
      POKEMON.PIKIPEK,
      POKEMON.TRUMBEAK,
      POKEMON.CORSOLA,
      POKEMON.REMORAID,
      POKEMON.GRUBBIN,
      POKEMON.CHARJABUG,
      POKEMON.ORICORIO,
      POKEMON.CUTIEFLY,
      POKEMON.RIBOMBEE,
      POKEMON.STANTLER,
      POKEMON.MORELULL,
      POKEMON.SHIINOTIC,
      POKEMON.BOUNSWEET,
      POKEMON.STEENEE,
      POKEMON.TSAREENA,
      POKEMON.ORANGURU,
      POKEMON.PASSIMIAN,
      POKEMON.WIMPOD,
      POKEMON.SANDYGAST,
      POKEMON.PALOSSAND,
      POKEMON.KOMALA,
      POKEMON.TOGEDEMARU,
      POKEMON.BRUXISH,
      POKEMON.JANGMO_O,
      POKEMON.GROOKEY,
      POKEMON.NOSEPASS,
      POKEMON.THWACKEY,
      POKEMON.RILLABOOM,
      POKEMON.SCORBUNNY,
      POKEMON.RABOOT,
      POKEMON.CINDERACE,
      POKEMON.SOBBLE,
      POKEMON.DRIZZILE,
      POKEMON.INTELEON,
      POKEMON.GREEDENT,
      POKEMON.ROOKIDEE,
      POKEMON.CORVISQUIRE,
      POKEMON.CORVIKNIGHT,
      POKEMON.WOOLOO,
      POKEMON.DUBWOOL,
      POKEMON.NUMEL,
      POKEMON.CAMERUPT,
      POKEMON.TORKOAL,
      POKEMON.SEVIPER,
      POKEMON.SIZZLIPEDE,
      POKEMON.CENTISKORCH,
      POKEMON.BARBOACH,
      POKEMON.WHISCASH,
      POKEMON.CORPHISH,
      POKEMON.CRAWDAUNT,
      POKEMON.HATENNA,
      POKEMON.HATTREM,
      POKEMON.HATTERENE,
      POKEMON.IMPIDIMP,
      POKEMON.MORGREM,
      POKEMON.GRIMMSNARL,
      POKEMON.TROPIUS,
      POKEMON.CHIMECHO,
      POKEMON.RELICANTH,
      POKEMON.SNEASLER,
      POKEMON.SPRIGATITO,
      POKEMON.FLORAGATO,
      POKEMON.MEOWSCARADA,
      POKEMON.FUECOCO,
      POKEMON.CROCALOR,
      POKEMON.SKELEDIRGE,
      POKEMON.QUAXLY,
      POKEMON.QUAXWELL,
      POKEMON.QUAQUAVAL,
      POKEMON.LECHONK,
      POKEMON.OINKOLOGNE,
      POKEMON.NYMBLE,
      POKEMON.CRANIDOS,
      POKEMON.LOKIX,
      POKEMON.PAWMI,
      POKEMON.PAWMO,
      POKEMON.BURMY,
      POKEMON.FIDOUGH,
      POKEMON.DACHSBUN,
      POKEMON.SMOLIV,
      POKEMON.DOLLIV,
      POKEMON.PACHIRISU,
      POKEMON.BUIZEL,
      POKEMON.ARBOLIVA,
      POKEMON.FLOATZEL,
      POKEMON.CHERUBI,
      POKEMON.CHERRIM,
      POKEMON.SHELLOS,
      POKEMON.GASTRODON,
      POKEMON.CHARCADET,
      POKEMON.CERULEDGE,
      POKEMON.TADBULB,
      POKEMON.BELLIBOLT,
      POKEMON.TOEDSCOOL,
      POKEMON.WIGLETT,
      POKEMON.WUGTRIO,
      POKEMON.CARNIVINE,
      POKEMON.CETITAN,
      POKEMON.KINGAMBIT,
      POKEMON.BAXCALIBUR,
      POKEMON.PURRLOIN,
      POKEMON.LIEPARD,
    ]),
  },
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 100,
    maxIV: 100,
    onlyShiny: false,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: true,
    name: '100%',
    distance: 10,
    priority: 0,
  },
];
