/**
 * The filters PGSharp saves — which spawns the radar and the nearby feed are looking for. Unlike a control's position,
 * which is a Java Float, each of these is stored as one JSON string; they are kept as objects here so every field reads
 * and diffs on its own, and JSON.stringify re-emits the compact string PGSharp wrote where they are put in the backup.
 * That re-emission goes field by field in source order, so the order below is part of the value and must not be
 * rearranged. Every value is taken verbatim from a known-good backup and none is user-editable.
 */

import POKEMON from './pokemon.js';

/**
 * A filter's species list, checked. A constant pokemon.js does not define reads as undefined rather than failing, and
 * would reach the backup as a null where a species should be, so it stops here instead. The value is all we are handed
 * — the constant's name is gone by then — so the error gives the position to look at.
 */
function species(numbers) {
  const at = numbers.findIndex((n) => !Number.isInteger(n));

  if (at !== -1) {
    throw new Error(`species #${at + 1} is not a POKEMON constant — check it against pokemon.js`);
  }

  return numbers;
}

/**
 * The nearby radar's own filter, stored under "hlscan" — it rides along with the radar button's position rather than
 * ticking separately, since the button is what carries it.
 */
export const SCAN_CONFIG = {
  shiny: true,
  minlv: 1,
  maxlv: 36,
  miniv: 0,
  maxiv: 100,
  checkAll: true,
  onlyShiny: true,
  name: 'Nearby Radar',
  birds: true,
  attrMode: 0,
  minatk: 0,
  maxatk: 15,
  mindef: 0,
  maxdef: 15,
  minsta: 0,
  maxsta: 15,
  showShinyOnly: true,
  loadShiny: true,
  notify: true,
  stop: true,
  pgp: true,
};

/**
 * The nearby feed's filter list, stored under "hlfeeds" — the named filters the feed matches spawns against, as one
 * JSON array. "Shiny Hunting" watches its own list of species for a shiny within 5 km; "100%" watches every species for
 * a perfect one within 10 km and is the only one that notifies. That species list is written in dex order; PGSharp
 * wrote it in neither dex nor alphabetical order, and reads it back as the set of species it holds, so the order it is
 * stored in is ours to pick.
 */
export const FEED_FILTERS = [
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 0,
    maxIV: 100,
    onlyShiny: true,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: false,
    name: 'Shiny Hunting',
    distance: 5,
    priority: 0,
    pokemons: species([
      // Generation 1
      POKEMON.PARAS,
      POKEMON.SLOWPOKE,
      POKEMON.SLOWBRO,
      POKEMON.DODUO,
      POKEMON.DODRIO,
      POKEMON.GOLDEEN,
      POKEMON.SEAKING,
      POKEMON.STARYU,
      POKEMON.STARMIE,
      POKEMON.SNORLAX,

      // Generation 2
      POKEMON.UNOWN,
      POKEMON.GIRAFARIG,
      POKEMON.REMORAID,
      POKEMON.STANTLER,
      
      // Generation 3
      POKEMON.NOSEPASS,
      POKEMON.TORKOAL,
      POKEMON.SEVIPER,
      POKEMON.BARBOACH,
      POKEMON.WHISCASH,
      POKEMON.CORPHISH,
      POKEMON.CRAWDAUNT,
      POKEMON.TROPIUS,
      POKEMON.RELICANTH,
      
      // Generation 4
      POKEMON.CRANIDOS,
      POKEMON.RAMPARDOS,
      POKEMON.BURMY,
      POKEMON.PACHIRISU,
      POKEMON.BUIZEL,
      POKEMON.FLOATZEL,
      POKEMON.CHERUBI,
      POKEMON.CHERRIM,
      POKEMON.CARNIVINE,
      
      // Generation 5
      POKEMON.PURRLOIN,
      POKEMON.LIEPARD,
      POKEMON.PANPOUR,
      POKEMON.PIDOVE,
      POKEMON.TRANQUILL,
      POKEMON.UNFEZANT,
      POKEMON.ROGGENROLA,
      POKEMON.BOLDORE,
      POKEMON.WOOBAT,
      POKEMON.SWOOBAT,
      POKEMON.DRILBUR,
      POKEMON.EXCADRILL,
      POKEMON.AUDINO,
      POKEMON.TYMPOLE,
      POKEMON.PALPITOAD,
      POKEMON.SEISMITOAD,
      POKEMON.SEWADDLE,
      POKEMON.SWADLOON,
      POKEMON.LEAVANNY,
      POKEMON.VENIPEDE,
      POKEMON.WHIRLIPEDE,
      POKEMON.COTTONEE,
      POKEMON.WHIMSICOTT,
      POKEMON.MARACTUS,
      POKEMON.SCRAGGY,
      POKEMON.SCRAFTY,
      POKEMON.SIGILYPH,
      POKEMON.YAMASK,
      POKEMON.COFAGRIGUS,
      POKEMON.TIRTOUGA,
      POKEMON.ARCHEN,
      POKEMON.ZORUA,
      POKEMON.DEERLING,
      POKEMON.SAWSBUCK,
      POKEMON.KARRABLAST,
      POKEMON.FRILLISH,
      POKEMON.JELLICENT,
      POKEMON.JOLTIK,
      POKEMON.GALVANTULA,
      POKEMON.TYNAMO,
      POKEMON.EELEKTRIK,
      POKEMON.ELGYEM,
      POKEMON.BEHEEYEM,
      POKEMON.AXEW,
      POKEMON.FRAXURE,
      POKEMON.HAXORUS,
      POKEMON.SHELMET,
      POKEMON.MIENFOO,
      POKEMON.MIENSHAO,
      POKEMON.GOLETT,
      POKEMON.BISHARP,
      POKEMON.RUFFLET,
      POKEMON.BRAVIARY,
      POKEMON.DURANT,
      POKEMON.LARVESTA,

      // Generation 6
      POKEMON.FENNEKIN,
      POKEMON.FROAKIE,
      POKEMON.GRENINJA,
      POKEMON.BUNNELBY,
      POKEMON.DIGGERSBY,
      POKEMON.VIVILLON,
      POKEMON.FLABEBE,
      POKEMON.FLOETTE,
      POKEMON.SKIDDO,
      POKEMON.GOGOAT,
      POKEMON.PANCHAM,
      POKEMON.FURFROU,
      POKEMON.SPRITZEE,
      POKEMON.AROMATISSE,
      POKEMON.SWIRLIX,
      POKEMON.SLURPUFF,
      POKEMON.BINACLE,
      POKEMON.BARBARACLE,
      POKEMON.SKRELP,
      POKEMON.CLAUNCHER,
      POKEMON.HELIOPTILE,
      POKEMON.TYRUNT,
      POKEMON.TYRANTRUM,
      POKEMON.AMAURA,
      POKEMON.HAWLUCHA,
      POKEMON.DEDENNE,
      POKEMON.CARBINK,
      POKEMON.GOOMY,
      POKEMON.SLIGGOO,
      POKEMON.GOODRA,
      POKEMON.KLEFKI,
      POKEMON.PHANTUMP,
      POKEMON.PUMPKABOO,
      POKEMON.BERGMITE,
      POKEMON.AVALUGG,
      POKEMON.NOIBAT,
      
      // Generation 7
      POKEMON.ROWLET,
      POKEMON.DARTRIX,
      POKEMON.DECIDUEYE,
      POKEMON.LITTEN,
      POKEMON.TORRACAT,
      POKEMON.INCINEROAR,
      POKEMON.POPPLIO,
      POKEMON.BRIONNE,
      POKEMON.PIKIPEK,
      POKEMON.TRUMBEAK,
      POKEMON.GRUBBIN,
      POKEMON.CHARJABUG,
      POKEMON.VIKAVOLT,
      POKEMON.ORICORIO,
      POKEMON.CUTIEFLY,
      POKEMON.RIBOMBEE,
      POKEMON.MORELULL,
      POKEMON.SHIINOTIC,
      POKEMON.BOUNSWEET,
      POKEMON.TSAREENA,
      POKEMON.ORANGURU,
      POKEMON.PASSIMIAN,
      POKEMON.WIMPOD,
      POKEMON.GOLISOPOD,
      POKEMON.SANDYGAST,
      POKEMON.PALOSSAND,
      POKEMON.KOMALA,
      POKEMON.TOGEDEMARU,
      POKEMON.BRUXISH,
      POKEMON.JANGMO_O,

      // Generation 8
      POKEMON.GROOKEY,
      POKEMON.THWACKEY,
      POKEMON.RILLABOOM,
      POKEMON.SCORBUNNY,
      POKEMON.RABOOT,
      POKEMON.CINDERACE,
      POKEMON.SOBBLE,
      POKEMON.DRIZZILE,
      POKEMON.INTELEON,
      POKEMON.ROOKIDEE,
      POKEMON.CORVISQUIRE,
      POKEMON.CORVIKNIGHT,
      POKEMON.WOOLOO,
      POKEMON.DUBWOOL,
      POKEMON.SIZZLIPEDE,
      POKEMON.CENTISKORCH,
      POKEMON.HATENNA,
      POKEMON.HATTREM,
      POKEMON.HATTERENE,
      POKEMON.IMPIDIMP,
      POKEMON.MORGREM,
      POKEMON.GRIMMSNARL,
      POKEMON.SIRFETCHD,
      POKEMON.RUNERIGUES,
      POKEMON.SNOM,
      POKEMON.FROSMOTH,
      POKEMON.SNEASLER,
      POKEMON.OVERQWIL,

      // Generation 9
      POKEMON.SPRIGATITO,
      POKEMON.FLORAGATO,
      POKEMON.FUECOCO,
      POKEMON.CROCALOR,
      POKEMON.SKELEDIRGE,
      POKEMON.QUAXLY,
      POKEMON.QUAXWELL,
      POKEMON.QUAQUAVAL,
      POKEMON.LECHONK,
      POKEMON.OINKOLOGNE,
      POKEMON.NYMBLE,
      POKEMON.PAWMI,
      POKEMON.PAWMO,
      POKEMON.FIDOUGH,
      POKEMON.DACHSBUN,
      POKEMON.SMOLIV,
      POKEMON.DOLLIV,
      POKEMON.TADBULB,
      POKEMON.BELLIBOLT,
      POKEMON.TOEDSCOOL,
      POKEMON.TOEDSCRUEL,
      POKEMON.WIGLETT,
      POKEMON.ANNIHILAPE,
      POKEMON.CLODSIRE,
      POKEMON.FRIGIBAX,
      POKEMON.ARCTIBAX,
      POKEMON.BAXCALIBUR
    ]),
  },
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 100,
    maxIV: 100,
    onlyShiny: false,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: true,
    name: '100%',
    distance: 10,
    priority: 0,
  },
];
