/**
 * The filters PGSharp saves — which spawns the radar and the nearby feed are looking for. Unlike a control's position,
 * which is a Java Float, each of these is stored as one JSON string; they are kept as objects here so every field
 * reads and diffs on its own, and JSON.stringify re-emits the compact string PGSharp wrote where they are put in the
 * backup. That re-emission goes field by field in source order, so the order below is part of the value and must not
 * be rearranged.
 */

import POKEMON, { Pokemon, filterReleased, filterShinyEligible, filterWildSpawns, GALAR, HISUI, PALDEA } from './pokemon.js';

/**
 * A filter's species list, checked, narrowed and collapsed to one entry per species. A form or a region the species
 * does not have has already thrown by the time we are called, so what is left to catch is a name pokemon.js does not
 * define at all, which reads as undefined and would reach the backup as a null where a species should be. The value is
 * all we are handed — the constant's name is gone by then — so the error gives the position to look at.
 *
 * Every `keep` given has to hold for an entry to stay, which is how a filter drops what has no shiny to find or what
 * the wild never turns up. They run before the list collapses, so a species listed twice — once as a form that
 * survives them and once as one that does not — keeps the form that survives rather than whichever came first.
 *
 * A form is a Pokemon of its own carrying the dex number of the species it belongs to, since that number is all
 * PGSharp stores, so a list naming several forms of one species names that number several times. The names are worth
 * keeping — they say which forms the list is for — but the repeats are not, so the first of each number survives and
 * the rest go, leaving the list PGSharp itself would write.
 */
function species(entries, ...keep) {
  const at = entries.findIndex((entry) => !(entry instanceof Pokemon));

  if (at !== -1) {
    throw new Error(`species #${at + 1} is not a POKEMON constant — check it against pokemon.js`);
  }

  const kept = entries.filter((entry) => keep.every((predicate) => predicate(entry)));

  return [...new Map(kept.map((entry) => [Number(entry), entry])).values()];
}

/**
 * The nearby radar's own filter, stored under "hlscan" — it rides along with the radar button's position rather than
 * ticking separately, since the button is what carries it.
 */
export const SCAN_CONFIG = {
  shiny: true,
  minlv: 1,
  maxlv: 36,
  miniv: 0,
  maxiv: 100,
  checkAll: true,
  onlyShiny: true,
  name: 'Nearby Radar',
  birds: true,
  attrMode: 0,
  minatk: 0,
  maxatk: 15,
  mindef: 0,
  maxdef: 15,
  minsta: 0,
  maxsta: 15,
  showShinyOnly: true,
  loadShiny: true,
  notify: true,
  stop: true,
  pgp: true,
};

export const FEED_FILTERS = [
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 0,
    maxIV: 100,
    onlyShiny: true,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: false,
    name: 'Shiny Hunting',
    distance: 80,
    priority: 1,

    // prettier-ignore
    pokemons: species([
      // Generation 1
      POKEMON.GROWLITHE.region(HISUI), POKEMON.ARCANINE.region(HISUI),
      POKEMON.PONYTA.region(GALAR), POKEMON.RAPIDASH.region(GALAR),
      POKEMON.SLOWPOKE.region(GALAR), POKEMON.SLOWBRO.region(GALAR),
      POKEMON.DODUO, POKEMON.DODRIO,
      POKEMON.SEEL,
      POKEMON.VOLTORB.region(HISUI), POKEMON.ELECTRODE.region(HISUI),
      POKEMON.WEEZING.region(GALAR),
      POKEMON.HORSEA, POKEMON.SEADRA,
      POKEMON.MR_MIME.region(GALAR),
      ...POKEMON.TAUROS.region(PALDEA).forms('COMBAT_BREED', 'BLAZE_BREED', 'AQUA_BREED'),
      POKEMON.ZAPDOS.region(GALAR),
      POKEMON.MOLTRES.region(GALAR),

      // Generation 2
      POKEMON.TYPHLOSION.region(HISUI),
      POKEMON.SLOWKING.region(GALAR),
      ...POKEMON.UNOWN.forms('A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'EXCLAMATION_MARK', 'QUESTION_MARK'),
      POKEMON.GIRAFARIG,
      POKEMON.SNEASEL.region(HISUI),
      POKEMON.CORSOLA.region(GALAR),
      POKEMON.REMORAID, POKEMON.OCTILLERY,
      POKEMON.MANTINE,
      POKEMON.STANTLER,
      POKEMON.SMEARGLE,
      POKEMON.TYROGUE,

      // Generation 3
      POKEMON.ZIGZAGOON.region(GALAR), POKEMON.LINOONE.region(GALAR),
      POKEMON.NINCADA, POKEMON.NINJASK, POKEMON.SHEDINJA,
      ...POKEMON.SPINDA.forms('PATTERN_1', 'PATTERN_2', 'PATTERN_3', 'PATTERN_5', 'PATTERN_6', 'PATTERN_7', 'PATTERN_9', 'PATTERN_10', 'PATTERN_11', 'PATTERN_12', 'PATTERN_13', 'PATTERN_14', 'PATTERN_15', 'PATTERN_16', 'PATTERN_17', 'PATTERN_18', 'PATTERN_19', 'PATTERN_20'),
      POKEMON.BARBOACH, POKEMON.WHISCASH,
      ...POKEMON.CASTFORM.forms('SUNNY', 'SNOWY'),
      POKEMON.TROPIUS,
      POKEMON.RELICANTH,
      POKEMON.JIRACHI,

      // Generation 4
      POKEMON.CRANIDOS, POKEMON.RAMPARDOS,
      ...POKEMON.BURMY.forms('PLANT_CLOAK', 'SANDY_CLOAK', 'TRASH_CLOAK'),
      ...POKEMON.WORMADAM.forms('PLANT_CLOAK', 'SANDY_CLOAK', 'TRASH_CLOAK'),
      POKEMON.MOTHIM,
      POKEMON.PACHIRISU,
      POKEMON.BUIZEL, POKEMON.FLOATZEL,
      POKEMON.CHERUBI, ...POKEMON.CHERRIM.forms('OVERCAST', 'SUNNY'),
      POKEMON.CHINGLING,
      POKEMON.MIME_JR,
      POKEMON.HAPPINY,
      POKEMON.SPIRITOMB,
      POKEMON.MUNCHLAX,
      POKEMON.HIPPOPOTAS.form('FEMALE'), POKEMON.HIPPOWDON.form('FEMALE'),
      POKEMON.CARNIVINE,
      POKEMON.MANTYKE,
      ...POKEMON.ROTOM.forms('NORMAL', 'HEAT', 'WASH', 'FROST', 'FAN', 'MOW'),
      POKEMON.PHIONE, POKEMON.MANAPHY,
      ...POKEMON.SHAYMIN.forms('LAND_FORME', 'SKY_FORME'),
      ...POKEMON.ARCEUS.forms('NORMAL', 'BUG', 'DARK', 'DRAGON', 'ELECTRIC', 'FAIRY', 'FIGHTING', 'FIRE', 'FLYING', 'GHOST', 'GRASS', 'GROUND', 'ICE', 'POISON', 'PSYCHIC', 'ROCK', 'STEEL', 'WATER'),

      // Generation 5
      POKEMON.VICTINI,
      POKEMON.PURRLOIN, POKEMON.LIEPARD,
      POKEMON.PANSAGE, POKEMON.SIMISAGE,
      POKEMON.PANSEAR, POKEMON.SIMISEAR,
      POKEMON.PIDOVE, POKEMON.TRANQUILL, POKEMON.UNFEZANT,
      POKEMON.ROGGENROLA, POKEMON.BOLDORE, POKEMON.GIGALITH,
      POKEMON.PETILIL, POKEMON.LILLIGANT, POKEMON.LILLIGANT.region(HISUI),
      ...POKEMON.BASCULIN.forms('RED_STRIPED', 'BLUE_STRIPED', 'WHITE_STRIPED'),
      POKEMON.YAMASK.region(GALAR),
      POKEMON.TIRTOUGA, POKEMON.CARRACOSTA,
      POKEMON.ARCHEN, POKEMON.ARCHEOPS,
      POKEMON.ZORUA.region(HISUI), POKEMON.ZOROARK.region(HISUI),
      POKEMON.SOLOSIS, POKEMON.DUOSION, POKEMON.REUNICLUS,
      ...POKEMON.DEERLING.forms('SPRING_FORM', 'AUTUMN_FORM', 'WINTER_FORM'),
      ...POKEMON.SAWSBUCK.forms('SPRING_FORM', 'AUTUMN_FORM', 'WINTER_FORM'),
      POKEMON.KARRABLAST, POKEMON.ESCAVALIER,
      POKEMON.FRILLISH.form('MALE'), POKEMON.JELLICENT.form('MALE'),
      POKEMON.AXEW, POKEMON.FRAXURE, POKEMON.HAXORUS,
      POKEMON.CRYOGONAL,
      POKEMON.SHELMET, POKEMON.ACCELGOR,
      POKEMON.MIENFOO, POKEMON.MIENSHAO,
      POKEMON.GOLETT, POKEMON.GOLURK,
      POKEMON.PAWNIARD, POKEMON.BISHARP,
      POKEMON.RUFFLET, POKEMON.BRAVIARY, POKEMON.BRAVIARY.region(HISUI),
      POKEMON.LARVESTA, POKEMON.VOLCARONA,
      POKEMON.TORNADUS.form('THERIAN_FORME'),
      POKEMON.RESHIRAM,
      POKEMON.LANDORUS.form('THERIAN_FORME'),
      ...POKEMON.KYUREM.forms('BLACK', 'WHITE'),
      POKEMON.KELDEO,
      POKEMON.MELOETTA,
      ...POKEMON.GENESECT.forms('SHOCK_DRIVE', 'BURN_DRIVE', 'CHILL_DRIVE', 'DOUSE_DRIVE'),

      // Generation 6
      POKEMON.BUNNELBY, POKEMON.DIGGERSBY,
      POKEMON.SCATTERBUG, POKEMON.SPEWPA, ...POKEMON.VIVILLON.forms(
        'ARCHIPELAGO',                                                                                                    
        'CONTINENTAL',                                                                                                    
        'ELEGANT',                                                                                                        
        'FANCY',
        'GARDEN',                                                                                                         
        'HIGH_PLAINS',                                                                                                    
        'ICY_SNOW',                                                                                                       
        'JUNGLE',                                                                                                         
        'MARINE',                                                                                                         
        'MEADOW',                                                                                                         
        'MODERN',                                                                                                         
        'MONSOON',                                                                                                        
        'OCEAN',                                                                                                          
        'POLAR',                                                                                                          
        'RIVER',                                                                                                          
        'SANDSTORM',                                                                                                      
        'SAVANNA',                                                                                                        
        'SUN',                                                                                                            
        'TUNDRA',
      ),
      ...POKEMON.FLABEBE.forms('RED_FLOWER', 'YELLOW_FLOWER', 'ORANGE_FLOWER', 'BLUE_FLOWER', 'WHITE_FLOWER'),
      ...POKEMON.FLOETTE.forms('RED_FLOWER', 'YELLOW_FLOWER', 'ORANGE_FLOWER', 'BLUE_FLOWER', 'WHITE_FLOWER'),
      ...POKEMON.FLORGES.forms('RED_FLOWER', 'YELLOW_FLOWER', 'ORANGE_FLOWER', 'BLUE_FLOWER', 'WHITE_FLOWER'),
      POKEMON.HONEDGE, POKEMON.DOUBLADE, ...POKEMON.AEGISLASH.forms('SHIELD_FORME', 'BLADE_FORME'),
      POKEMON.SWIRLIX, POKEMON.SLURPUFF,
      POKEMON.SKRELP, POKEMON.DRAGALGE,
      POKEMON.HAWLUCHA,
      POKEMON.GOOMY, POKEMON.SLIGGOO, POKEMON.SLIGGOO.region(HISUI), POKEMON.GOODRA, POKEMON.GOODRA.region(HISUI),
      ...POKEMON.PUMPKABOO.forms('SMALL_VARIETY', 'LARGE_VARIETY', 'JUMBO_VARIETY'),
      ...POKEMON.GOURGEIST.forms('SMALL_VARIETY', 'LARGE_VARIETY', 'JUMBO_VARIETY'),
      POKEMON.XERNEAS,
      POKEMON.YVELTAL,
      ...POKEMON.ZYGARDE.forms('TEN_PERCENT_FORME', 'FIFTY_PERCENT_FORME', 'COMPLETE_FORME'),
      POKEMON.DIANCIE,
      ...POKEMON.HOOPA.forms('CONFINED', 'UNBOUND'),
      POKEMON.VOLCANION,

      // Generation 7
      POKEMON.ROWLET, POKEMON.DARTRIX, POKEMON.DECIDUEYE, POKEMON.DECIDUEYE.region(HISUI),
      POKEMON.POPPLIO, POKEMON.BRIONNE, POKEMON.PRIMARINA,
      POKEMON.PIKIPEK, POKEMON.TRUMBEAK, POKEMON.TOUCANNON,
      POKEMON.GRUBBIN, POKEMON.CHARJABUG, POKEMON.VIKAVOLT,
      POKEMON.CRABRAWLER, POKEMON.CRABOMINABLE,
      ...POKEMON.ORICORIO.forms('BAILE_STYLE', 'SENSU_STYLE'),
      POKEMON.CUTIEFLY, POKEMON.RIBOMBEE,
      ...POKEMON.WISHIWASHI.forms('SOLO_FORM', 'SCHOOL_FORM'),
      POKEMON.MUDBRAY, POKEMON.MUDSDALE,
      POKEMON.MORELULL, POKEMON.SHIINOTIC,
      POKEMON.SALANDIT, POKEMON.SALAZZLE,
      POKEMON.BOUNSWEET, POKEMON.STEENEE, POKEMON.TSAREENA,
      POKEMON.PASSIMIAN,
      POKEMON.SANDYGAST, POKEMON.PALOSSAND,
      // UP TO HERE
      POKEMON.PYUKUMUKU,
      POKEMON.TYPE_NULL, POKEMON.SILVALLY,
      POKEMON.MINIOR,
      POKEMON.MIMIKYU.forms('DISGUISED_FORM', 'BUSTED_FORM'),
      POKEMON.DHELMISE,
      POKEMON.JANGMO_O, POKEMON.HAKAMO_O, POKEMON.KOMMO_O,
      POKEMON.TAPU_KOKO,
      POKEMON.TAPU_LELE,
      POKEMON.TAPU_BULU,
      POKEMON.TAPU_FINI,
      POKEMON.COSMOG, POKEMON.COSMOEM,
      POKEMON.NIHILEGO,
      POKEMON.XURKITREE,
      POKEMON.CELESTEELA,
      POKEMON.KARTANA,
      ...POKEMON.NECROZMA.forms('DUSK_MANE', 'DAWN_WINGS', 'ULTRA')
      POKEMON.POIPOLE, POKEMON.NAGANADEL,
      POKEMON.STAKATAKA,
      POKEMON.BLACEPHALON,
      POKEMON.ZERAORA,

      // Generation 8
      POKEMON.GROOKEY, POKEMON.THWACKEY, POKEMON.RILLABOOM,
      POKEMON.BLIPBUG, POKEMON.DOTTLER, POKEMON.ORBEETLE,
      POKEMON.GOSSIFLEUR, POKEMON.ELDEGOSS,
      POKEMON.CHEWTLE, POKEMON.DREDNAW,
      POKEMON.YAMPER, POKEMON.BOLTUND,
      POKEMON.ROLYCOLY, POKEMON.CARKOL, POKEMON.COALOSSAL,
      POKEMON.APPLIN, POKEMON.FLAPPLE, POKEMON.APPLETUN,
      POKEMON.SILICOBRA, POKEMON.SANDACONDA,
      POKEMON.CRAMORANT,
      POKEMON.ARROKUDA, POKEMON.BARRASKEWDA,
      POKEMON.TOXEL, ...POKEMON.TOXTRICITY.forms('AMPED_FORM', 'LOW_KEY_FORM'),
      POKEMON.SIZZLIPEDE, POKEMON.CENTISKORCH,
      POKEMON.CLOBBOPUS, POKEMON.GRAPPLOCT,
      ...POKEMON.SINISTEA.forms('PHONY_FORM', 'ANTIQUE_FORM'), ...POKEMON.POLTEAGEIST.forms('PHONY_FORM', 'ANTIQUE_FORM'),
      POKEMON.IMPIDIMP, POKEMON.MORGREM, POKEMON.GRIMMSNARL,
      POKEMON.OBSTAGOON,
      POKEMON.CURSOLA,
      POKEMON.MR_RIME,
      POKEMON.RUNERIGUS,
      POKEMON.MILCERY, POKEMON.ALCREMIE,
      POKEMON.PINCURCHIN,
      POKEMON.SNOM, POKEMON.FROSMOTH,
      POKEMON.STONJOURNER,
      POKEMON.EISCUE.forms('ICE_FACE', 'NOICE_FACE'),
      POKEMON.INDEEDEE,
      POKEMON.MORPEKO.forms('FULL_BELLY_MODE', 'HANGRY_MODE'),
      POKEMON.CUFANT, POKEMON.COPPERAJAH,
      POKEMON.DRACOZOLT,
      POKEMON.ARCTOZOLT,
      POKEMON.DRACOVISH,
      POKEMON.ARCTOVISH,
      POKEMON.DURALUDON,
      POKEMON.DREEPY, POKEMON.DRAKLOAK, POKEMON.DRAGAPULT,
      POKEMON.ZACIAN.form('CROWNED_SWORD'),
      POKEMON.ZAMAZENTA.form('CROWNED_SHIELD'),
      ...POKEMON.ETERNATUS.forms('NORMAL', 'ETERNAMAX'),
      POKEMON.KUBFU, ...POKEMON.URSHIFU.forms('SINGLE_STRIKE_STYLE', 'RAPID_STRIKE_STYLE'),
      POKEMON.ZARUDE,
      POKEMON.GLASTRIER,
      POKEMON.SPECTRIER,
      ...POKEMON.CALYREX.forms('NORMAL', 'ICE_RIDER', 'SHADOW_RIDER'),
      POKEMON.URSALUNA,
      POKEMON.BASCULEGION,
      POKEMON.SNEASLER,
      ...POKEMON.ENAMORUS.forms('INCARNATE_FORME', 'THERIAN_FORME'),

      // Generation 9
      POKEMON.FUECOCO, POKEMON.CROCALOR, POKEMON.SKELEDIRGE,
      POKEMON.QUAXLY, POKEMON.QUAXWELL, POKEMON.QUAQUAVAL,
      POKEMON.TAROUNTULA, POKEMON.SPIDOPS,
      POKEMON.TANDEMAUS, ...POKEMON.MAUSHOLD.forms('FAMILY_OF_THREE', 'FAMILY_OF_FOUR'),
      POKEMON.FIDOUGH, POKEMON.DACHSBUN,
      POKEMON.SMOLIV, POKEMON.DOLLIV, POKEMON.ARBOLIVA,
      ...POKEMON.SQUAWKABILLY.forms('GREEN_PLUMAGE', 'BLUE_PLUMAGE', 'YELLOW_PLUMAGE', 'WHITE_PLUMAGE'),
      POKEMON.NACLI, POKEMON.NACLSTACK, POKEMON.GARGANACL,
      POKEMON.CHARCADET, POKEMON.ARMAROUGE, POKEMON.CERULEDGE,
      POKEMON.TADBULB, POKEMON.BELLIBOLT,
      POKEMON.WATTREL, POKEMON.KILOWATTREL,
      POKEMON.MASCHIEF, POKEMON.MABOSSTIFF,
      POKEMON.SHROODLE, POKEMON.GRAFAIAI,
      POKEMON.BRAMBLIN, POKEMON.BRAMBLEGHAST,
      POKEMON.TOEDSCOOL, POKEMON.TOEDSCRUEL,
      POKEMON.KLAWF,
      POKEMON.CAPSAKID, POKEMON.SCOVILLAIN,
      POKEMON.RELLOR, POKEMON.RABSCA,
      POKEMON.FLITTLE, POKEMON.ESPATHRA,
      POKEMON.TINKATINK, POKEMON.TINKATUFF, POKEMON.TINKATON,
      POKEMON.BOMBIRDIER,
      POKEMON.FINIZEN, ...POKEMON.PALAFIN.forms('ZERO_FORM', 'HERO_FORM'),
      POKEMON.VAROOM, POKEMON.REVAVROOM,
      POKEMON.CYCLIZAR,
      POKEMON.ORTHWORM,
      POKEMON.GLIMMET, POKEMON.GLIMMORA,
      POKEMON.GREAVARD, POKEMON.HOUNDSTONE,
      POKEMON.CETODDLE, POKEMON.CETITAN,
      POKEMON.VELUZA,
      ...POKEMON.TATSUGIRI.forms('CURLY_FORM', 'DROOPY_FORM', 'STRETCHY_FORM'),
      POKEMON.ANNIHILAPE,
      POKEMON.FARIGIRAF,
      POKEMON.KINGAMBIT,
      POKEMON.GREAT_TUSK,
      POKEMON.SCREAM_TAIL,
      POKEMON.BRUTE_BONNET,
      POKEMON.FLUTTER_MANE,
      POKEMON.SLITHER_WING,
      POKEMON.SANDY_SHOCKS,
      POKEMON.IRON_TREADS,
      POKEMON.IRON_BUNDLE,
      POKEMON.IRON_HANDS,
      POKEMON.IRON_JUGULIS,
      POKEMON.IRON_MOTH,
      POKEMON.IRON_THORNS,
      POKEMON.FRIGIBAX, POKEMON.ARCTIBAX, POKEMON.BAXCALIBUR,
      ...POKEMON.GIMMIGHOUL.forms('CHEST_FORM', 'ROAMING_FORM'), POKEMON.GHOLDENGO,
      POKEMON.WO_CHIEN,
      POKEMON.CHIEN_PAO,
      POKEMON.TING_LU,
      POKEMON.CHI_YU,
      POKEMON.ROARING_MOON,
      POKEMON.IRON_VALIANT,
      POKEMON.KORAIDON,
      POKEMON.MIRAIDON,
      POKEMON.WALKING_WAKE,
      POKEMON.IRON_LEAVES,
      POKEMON.DIPPLIN,
      ...POKEMON.POLTCHAGEIST.forms('COUNTERFEIT_FORM', 'ARTISAN_FORM'),
      ...POKEMON.SINISTCHA.forms('COUNTERFEIT_FORM', 'ARTISAN_FORM'),
      POKEMON.OKIDOGI,
      POKEMON.MUKIDORI,
      POKEMON.FEZANDIPITI,
      POKEMON.OGERPON.form('TEAL_MASK').
      POKEMON.ARCHALUDON,
      POKEMON.HYDRAPPLE,
      POKEMON.GOUGING_FIRE,
      POKEMON.RAGING_BOLT,
      POKEMON.IRON_BOULDER,
      POKEMON.IRON_CROWN,
      ...POKEMON.TERAPAGOS.forms('NORMAL_FORM', 'TERASTAL_FORM', 'STELLAR_FORM'),
      POKEMON.PECHARUNT,
    ], filterReleased, filterShinyEligible, filterWildSpawns),
  },
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 0,
    maxIV: 100,
    onlyShiny: true,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: false,
    name: 'Regional Shiny Hunting',
    distance: 80,
    priority: 1,

    // prettier-ignore
    pokemons: species([
      // Generation 3
      POKEMON.TROPIUS,
      POKEMON.RELICANTH,

      // Generation 4
      POKEMON.PACHIRISU,
      POKEMON.CARNIVINE,

      // Generation 6
      POKEMON.HAWLUCHA,

      // Generation 7
      ...POKEMON.ORICORIO.forms('BAILE_STYLE', 'SENSU_STYLE'),
    ]),
  },
  {
    checkAll: false,
    level: 1,
    lvmax: 36,
    minIV: 100,
    maxIV: 100,
    onlyShiny: false,
    attrMode: 0,
    minatk: 0,
    maxatk: 15,
    mindef: 0,
    maxdef: 15,
    minsta: 0,
    maxsta: 15,
    gender: 0,
    form: 0,
    size: 0,
    notif: true,
    name: '100%',
    distance: 10,
    priority: 0,
  },
];
