/**
 * The National Pokédex — every species as a constant naming it. PGSharp stores a species as its dex number, which says
 * nothing on its own, so the filters in `pgsharp-filters.js` are written with these constants instead:
 * `POKEMON.PANPOUR` reads as the species it is, and a misspelling is a name the table does not define rather than a
 * number nothing checks.
 *
 * The whole dex is here rather than only the species in use, so a filter can name any of them without the table having
 * to be extended first. A constant is its English name uppercased, with the punctuation the games spell it with
 * dropped or turned into an underscore — `FARFETCHD`, `MR_MIME`, `NIDORAN_F`, `FLABEBE`, `TYPE_NULL` — which keeps all
 * 1025 distinct.
 *
 * A species also carries the forms and regional variants it comes in, declared on the entry itself, so everything
 * about a species is in one place rather than in a table off to the side.
 */

/** The regions a species can wear a variant of, valued at the adjective the games call that variant. */
export const ALOLA = 'Alolan';
export const GALAR = 'Galarian';
export const HISUI = 'Hisuian';
export const PALDEA = 'Paldean';

/**
 * One species: a dex number wearing the names of everything it can look like. Naming a form or a region asks for one
 * the species actually has and hands the species back, so a filter can say which form it means and still write the one
 * number PGSharp stores — `toJSON` sees to that, leaving `JSON.stringify` to emit the dex number and nothing else.
 */
export class Pokemon {
  #dex;
  #name = `#${0}`;
  #forms = new Set();
  #regions = new Set();

  constructor(dex) {
    this.#dex = dex;
    this.#name = `#${dex}`;
  }

  /** The forms this species comes in, spelled as the games spell them. */
  withForms(...names) {
    for (const name of names) {
      this.#forms.add(name);
    }

    return this;
  }

  /** The regions this species has a variant in. */
  withRegions(...regions) {
    for (const region of regions) {
      this.#regions.add(region);
    }

    return this;
  }

  /** Names this species for the errors below, from the constant it is bound to. */
  as(name) {
    this.#name = name;
    return this;
  }

  /** One of this species' forms. A name it does not have stops here rather than reaching the backup as a null. */
  form(name) {
    if (!this.#forms.has(name)) {
      throw new Error(`${this.#name} has no ${name} form — check it against pokemon.js`);
    }

    return this;
  }

  /** This species as one region sees it. A region it has no variant in stops here for the same reason. */
  region(region) {
    if (!this.#regions.has(region)) {
      throw new Error(`${this.#name} has no ${region} form — check it against pokemon.js`);
    }

    return this;
  }

  toJSON() {
    return this.#dex;
  }

  valueOf() {
    return this.#dex;
  }
}

const POKEMON = {
  BULBASAUR: new Pokemon(1),
  IVYSAUR: new Pokemon(2),
  VENUSAUR: new Pokemon(3),
  CHARMANDER: new Pokemon(4),
  CHARMELEON: new Pokemon(5),
  CHARIZARD: new Pokemon(6),
  SQUIRTLE: new Pokemon(7),
  WARTORTLE: new Pokemon(8),
  BLASTOISE: new Pokemon(9),
  CATERPIE: new Pokemon(10),
  METAPOD: new Pokemon(11),
  BUTTERFREE: new Pokemon(12),
  WEEDLE: new Pokemon(13),
  KAKUNA: new Pokemon(14),
  BEEDRILL: new Pokemon(15),
  PIDGEY: new Pokemon(16),
  PIDGEOTTO: new Pokemon(17),
  PIDGEOT: new Pokemon(18),
  RATTATA: new Pokemon(19).withRegions(ALOLA),
  RATICATE: new Pokemon(20).withRegions(ALOLA),
  SPEAROW: new Pokemon(21),
  FEAROW: new Pokemon(22),
  EKANS: new Pokemon(23),
  ARBOK: new Pokemon(24),
  PIKACHU: new Pokemon(25),
  RAICHU: new Pokemon(26).withRegions(ALOLA),
  SANDSHREW: new Pokemon(27).withRegions(ALOLA),
  SANDSLASH: new Pokemon(28).withRegions(ALOLA),
  NIDORAN_F: new Pokemon(29),
  NIDORINA: new Pokemon(30),
  NIDOQUEEN: new Pokemon(31),
  NIDORAN_M: new Pokemon(32),
  NIDORINO: new Pokemon(33),
  NIDOKING: new Pokemon(34),
  CLEFAIRY: new Pokemon(35),
  CLEFABLE: new Pokemon(36),
  VULPIX: new Pokemon(37).withRegions(ALOLA),
  NINETALES: new Pokemon(38).withRegions(ALOLA),
  JIGGLYPUFF: new Pokemon(39),
  WIGGLYTUFF: new Pokemon(40),
  ZUBAT: new Pokemon(41),
  GOLBAT: new Pokemon(42),
  ODDISH: new Pokemon(43),
  GLOOM: new Pokemon(44),
  VILEPLUME: new Pokemon(45),
  PARAS: new Pokemon(46),
  PARASECT: new Pokemon(47),
  VENONAT: new Pokemon(48),
  VENOMOTH: new Pokemon(49),
  DIGLETT: new Pokemon(50).withRegions(ALOLA),
  DUGTRIO: new Pokemon(51).withRegions(ALOLA),
  MEOWTH: new Pokemon(52).withRegions(ALOLA, GALAR),
  PERSIAN: new Pokemon(53).withRegions(ALOLA),
  PSYDUCK: new Pokemon(54),
  GOLDUCK: new Pokemon(55),
  MANKEY: new Pokemon(56),
  PRIMEAPE: new Pokemon(57),
  GROWLITHE: new Pokemon(58).withRegions(HISUI),
  ARCANINE: new Pokemon(59).withRegions(HISUI),
  POLIWAG: new Pokemon(60),
  POLIWHIRL: new Pokemon(61),
  POLIWRATH: new Pokemon(62),
  ABRA: new Pokemon(63),
  KADABRA: new Pokemon(64),
  ALAKAZAM: new Pokemon(65),
  MACHOP: new Pokemon(66),
  MACHOKE: new Pokemon(67),
  MACHAMP: new Pokemon(68),
  BELLSPROUT: new Pokemon(69),
  WEEPINBELL: new Pokemon(70),
  VICTREEBEL: new Pokemon(71),
  TENTACOOL: new Pokemon(72),
  TENTACRUEL: new Pokemon(73),
  GEODUDE: new Pokemon(74).withRegions(ALOLA),
  GRAVELER: new Pokemon(75).withRegions(ALOLA),
  GOLEM: new Pokemon(76).withRegions(ALOLA),
  PONYTA: new Pokemon(77).withRegions(GALAR),
  RAPIDASH: new Pokemon(78).withRegions(GALAR),
  SLOWPOKE: new Pokemon(79).withRegions(GALAR),
  SLOWBRO: new Pokemon(80).withRegions(GALAR),
  MAGNEMITE: new Pokemon(81),
  MAGNETON: new Pokemon(82),
  FARFETCHD: new Pokemon(83).withRegions(GALAR),
  DODUO: new Pokemon(84),
  DODRIO: new Pokemon(85),
  SEEL: new Pokemon(86),
  DEWGONG: new Pokemon(87),
  GRIMER: new Pokemon(88).withRegions(ALOLA),
  MUK: new Pokemon(89).withRegions(ALOLA),
  SHELLDER: new Pokemon(90),
  CLOYSTER: new Pokemon(91),
  GASTLY: new Pokemon(92),
  HAUNTER: new Pokemon(93),
  GENGAR: new Pokemon(94),
  ONIX: new Pokemon(95),
  DROWZEE: new Pokemon(96),
  HYPNO: new Pokemon(97),
  KRABBY: new Pokemon(98),
  KINGLER: new Pokemon(99),
  VOLTORB: new Pokemon(100).withRegions(HISUI),
  ELECTRODE: new Pokemon(101).withRegions(HISUI),
  EXEGGCUTE: new Pokemon(102),
  EXEGGUTOR: new Pokemon(103).withRegions(ALOLA),
  CUBONE: new Pokemon(104),
  MAROWAK: new Pokemon(105).withRegions(ALOLA),
  HITMONLEE: new Pokemon(106),
  HITMONCHAN: new Pokemon(107),
  LICKITUNG: new Pokemon(108),
  KOFFING: new Pokemon(109),
  WEEZING: new Pokemon(110).withRegions(GALAR),
  RHYHORN: new Pokemon(111),
  RHYDON: new Pokemon(112),
  CHANSEY: new Pokemon(113),
  TANGELA: new Pokemon(114),
  KANGASKHAN: new Pokemon(115),
  HORSEA: new Pokemon(116),
  SEADRA: new Pokemon(117),
  GOLDEEN: new Pokemon(118),
  SEAKING: new Pokemon(119),
  STARYU: new Pokemon(120),
  STARMIE: new Pokemon(121),
  MR_MIME: new Pokemon(122).withRegions(GALAR),
  SCYTHER: new Pokemon(123),
  JYNX: new Pokemon(124),
  ELECTABUZZ: new Pokemon(125),
  MAGMAR: new Pokemon(126),
  PINSIR: new Pokemon(127),
  TAUROS: new Pokemon(128).withRegions(PALDEA).withForms('COMBAT_BREED', 'BLAZE_BREED', 'AQUA_BREED'),
  MAGIKARP: new Pokemon(129),
  GYARADOS: new Pokemon(130),
  LAPRAS: new Pokemon(131),
  DITTO: new Pokemon(132),
  EEVEE: new Pokemon(133),
  VAPOREON: new Pokemon(134),
  JOLTEON: new Pokemon(135),
  FLAREON: new Pokemon(136),
  PORYGON: new Pokemon(137),
  OMANYTE: new Pokemon(138),
  OMASTAR: new Pokemon(139),
  KABUTO: new Pokemon(140),
  KABUTOPS: new Pokemon(141),
  AERODACTYL: new Pokemon(142),
  SNORLAX: new Pokemon(143),
  ARTICUNO: new Pokemon(144).withRegions(GALAR),
  ZAPDOS: new Pokemon(145).withRegions(GALAR),
  MOLTRES: new Pokemon(146).withRegions(GALAR),
  DRATINI: new Pokemon(147),
  DRAGONAIR: new Pokemon(148),
  DRAGONITE: new Pokemon(149),
  MEWTWO: new Pokemon(150),
  MEW: new Pokemon(151),
  CHIKORITA: new Pokemon(152),
  BAYLEEF: new Pokemon(153),
  MEGANIUM: new Pokemon(154),
  CYNDAQUIL: new Pokemon(155),
  QUILAVA: new Pokemon(156),
  TYPHLOSION: new Pokemon(157).withRegions(HISUI),
  TOTODILE: new Pokemon(158),
  CROCONAW: new Pokemon(159),
  FERALIGATR: new Pokemon(160),
  SENTRET: new Pokemon(161),
  FURRET: new Pokemon(162),
  HOOTHOOT: new Pokemon(163),
  NOCTOWL: new Pokemon(164),
  LEDYBA: new Pokemon(165),
  LEDIAN: new Pokemon(166),
  SPINARAK: new Pokemon(167),
  ARIADOS: new Pokemon(168),
  CROBAT: new Pokemon(169),
  CHINCHOU: new Pokemon(170),
  LANTURN: new Pokemon(171),
  PICHU: new Pokemon(172),
  CLEFFA: new Pokemon(173),
  IGGLYBUFF: new Pokemon(174),
  TOGEPI: new Pokemon(175),
  TOGETIC: new Pokemon(176),
  NATU: new Pokemon(177),
  XATU: new Pokemon(178),
  MAREEP: new Pokemon(179),
  FLAAFFY: new Pokemon(180),
  AMPHAROS: new Pokemon(181),
  BELLOSSOM: new Pokemon(182),
  MARILL: new Pokemon(183),
  AZUMARILL: new Pokemon(184),
  SUDOWOODO: new Pokemon(185),
  POLITOED: new Pokemon(186),
  HOPPIP: new Pokemon(187),
  SKIPLOOM: new Pokemon(188),
  JUMPLUFF: new Pokemon(189),
  AIPOM: new Pokemon(190),
  SUNKERN: new Pokemon(191),
  SUNFLORA: new Pokemon(192),
  YANMA: new Pokemon(193),
  WOOPER: new Pokemon(194).withRegions(PALDEA),
  QUAGSIRE: new Pokemon(195),
  ESPEON: new Pokemon(196),
  UMBREON: new Pokemon(197),
  MURKROW: new Pokemon(198),
  SLOWKING: new Pokemon(199).withRegions(GALAR),
  MISDREAVUS: new Pokemon(200),
  UNOWN: new Pokemon(201).withForms(
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
    'EXCLAMATION_MARK',
    'QUESTION_MARK',
  ),
  WOBBUFFET: new Pokemon(202),
  GIRAFARIG: new Pokemon(203),
  PINECO: new Pokemon(204),
  FORRETRESS: new Pokemon(205),
  DUNSPARCE: new Pokemon(206),
  GLIGAR: new Pokemon(207),
  STEELIX: new Pokemon(208),
  SNUBBULL: new Pokemon(209),
  GRANBULL: new Pokemon(210),
  QWILFISH: new Pokemon(211).withRegions(HISUI),
  SCIZOR: new Pokemon(212),
  SHUCKLE: new Pokemon(213),
  HERACROSS: new Pokemon(214),
  SNEASEL: new Pokemon(215).withRegions(HISUI),
  TEDDIURSA: new Pokemon(216),
  URSARING: new Pokemon(217),
  SLUGMA: new Pokemon(218),
  MAGCARGO: new Pokemon(219),
  SWINUB: new Pokemon(220),
  PILOSWINE: new Pokemon(221),
  CORSOLA: new Pokemon(222).withRegions(GALAR),
  REMORAID: new Pokemon(223),
  OCTILLERY: new Pokemon(224),
  DELIBIRD: new Pokemon(225),
  MANTINE: new Pokemon(226),
  SKARMORY: new Pokemon(227),
  HOUNDOUR: new Pokemon(228),
  HOUNDOOM: new Pokemon(229),
  KINGDRA: new Pokemon(230),
  PHANPY: new Pokemon(231),
  DONPHAN: new Pokemon(232),
  PORYGON2: new Pokemon(233),
  STANTLER: new Pokemon(234),
  SMEARGLE: new Pokemon(235),
  TYROGUE: new Pokemon(236),
  HITMONTOP: new Pokemon(237),
  SMOOCHUM: new Pokemon(238),
  ELEKID: new Pokemon(239),
  MAGBY: new Pokemon(240),
  MILTANK: new Pokemon(241),
  BLISSEY: new Pokemon(242),
  RAIKOU: new Pokemon(243),
  ENTEI: new Pokemon(244),
  SUICUNE: new Pokemon(245),
  LARVITAR: new Pokemon(246),
  PUPITAR: new Pokemon(247),
  TYRANITAR: new Pokemon(248),
  LUGIA: new Pokemon(249),
  HO_OH: new Pokemon(250),
  CELEBI: new Pokemon(251),
  TREECKO: new Pokemon(252),
  GROVYLE: new Pokemon(253),
  SCEPTILE: new Pokemon(254),
  TORCHIC: new Pokemon(255),
  COMBUSKEN: new Pokemon(256),
  BLAZIKEN: new Pokemon(257),
  MUDKIP: new Pokemon(258),
  MARSHTOMP: new Pokemon(259),
  SWAMPERT: new Pokemon(260),
  POOCHYENA: new Pokemon(261),
  MIGHTYENA: new Pokemon(262),
  ZIGZAGOON: new Pokemon(263).withRegions(GALAR),
  LINOONE: new Pokemon(264).withRegions(GALAR),
  WURMPLE: new Pokemon(265),
  SILCOON: new Pokemon(266),
  BEAUTIFLY: new Pokemon(267),
  CASCOON: new Pokemon(268),
  DUSTOX: new Pokemon(269),
  LOTAD: new Pokemon(270),
  LOMBRE: new Pokemon(271),
  LUDICOLO: new Pokemon(272),
  SEEDOT: new Pokemon(273),
  NUZLEAF: new Pokemon(274),
  SHIFTRY: new Pokemon(275),
  TAILLOW: new Pokemon(276),
  SWELLOW: new Pokemon(277),
  WINGULL: new Pokemon(278),
  PELIPPER: new Pokemon(279),
  RALTS: new Pokemon(280),
  KIRLIA: new Pokemon(281),
  GARDEVOIR: new Pokemon(282),
  SURSKIT: new Pokemon(283),
  MASQUERAIN: new Pokemon(284),
  SHROOMISH: new Pokemon(285),
  BRELOOM: new Pokemon(286),
  SLAKOTH: new Pokemon(287),
  VIGOROTH: new Pokemon(288),
  SLAKING: new Pokemon(289),
  NINCADA: new Pokemon(290),
  NINJASK: new Pokemon(291),
  SHEDINJA: new Pokemon(292),
  WHISMUR: new Pokemon(293),
  LOUDRED: new Pokemon(294),
  EXPLOUD: new Pokemon(295),
  MAKUHITA: new Pokemon(296),
  HARIYAMA: new Pokemon(297),
  AZURILL: new Pokemon(298),
  NOSEPASS: new Pokemon(299),
  SKITTY: new Pokemon(300),
  DELCATTY: new Pokemon(301),
  SABLEYE: new Pokemon(302),
  MAWILE: new Pokemon(303),
  ARON: new Pokemon(304),
  LAIRON: new Pokemon(305),
  AGGRON: new Pokemon(306),
  MEDITITE: new Pokemon(307),
  MEDICHAM: new Pokemon(308),
  ELECTRIKE: new Pokemon(309),
  MANECTRIC: new Pokemon(310),
  PLUSLE: new Pokemon(311),
  MINUN: new Pokemon(312),
  VOLBEAT: new Pokemon(313),
  ILLUMISE: new Pokemon(314),
  ROSELIA: new Pokemon(315),
  GULPIN: new Pokemon(316),
  SWALOT: new Pokemon(317),
  CARVANHA: new Pokemon(318),
  SHARPEDO: new Pokemon(319),
  WAILMER: new Pokemon(320),
  WAILORD: new Pokemon(321),
  NUMEL: new Pokemon(322),
  CAMERUPT: new Pokemon(323),
  TORKOAL: new Pokemon(324),
  SPOINK: new Pokemon(325),
  GRUMPIG: new Pokemon(326),
  SPINDA: new Pokemon(327).withForms(
    'PATTERN_1',
    'PATTERN_2',
    'PATTERN_3',
    'PATTERN_4',
    'PATTERN_5',
    'PATTERN_6',
    'PATTERN_7',
    'PATTERN_8',
    'PATTERN_9',
    'PATTERN_10',
    'PATTERN_11',
    'PATTERN_12',
    'PATTERN_13',
    'PATTERN_14',
    'PATTERN_15',
    'PATTERN_16',
    'PATTERN_17',
    'PATTERN_18',
    'PATTERN_19',
    'PATTERN_20',
  ),
  TRAPINCH: new Pokemon(328),
  VIBRAVA: new Pokemon(329),
  FLYGON: new Pokemon(330),
  CACNEA: new Pokemon(331),
  CACTURNE: new Pokemon(332),
  SWABLU: new Pokemon(333),
  ALTARIA: new Pokemon(334),
  ZANGOOSE: new Pokemon(335),
  SEVIPER: new Pokemon(336),
  LUNATONE: new Pokemon(337),
  SOLROCK: new Pokemon(338),
  BARBOACH: new Pokemon(339),
  WHISCASH: new Pokemon(340),
  CORPHISH: new Pokemon(341),
  CRAWDAUNT: new Pokemon(342),
  BALTOY: new Pokemon(343),
  CLAYDOL: new Pokemon(344),
  LILEEP: new Pokemon(345),
  CRADILY: new Pokemon(346),
  ANORITH: new Pokemon(347),
  ARMALDO: new Pokemon(348),
  FEEBAS: new Pokemon(349),
  MILOTIC: new Pokemon(350),
  CASTFORM: new Pokemon(351).withForms('NORMAL', 'SUNNY', 'RAINY', 'SNOWY'),
  KECLEON: new Pokemon(352),
  SHUPPET: new Pokemon(353),
  BANETTE: new Pokemon(354),
  DUSKULL: new Pokemon(355),
  DUSCLOPS: new Pokemon(356),
  TROPIUS: new Pokemon(357),
  CHIMECHO: new Pokemon(358),
  ABSOL: new Pokemon(359),
  WYNAUT: new Pokemon(360),
  SNORUNT: new Pokemon(361),
  GLALIE: new Pokemon(362),
  SPHEAL: new Pokemon(363),
  SEALEO: new Pokemon(364),
  WALREIN: new Pokemon(365),
  CLAMPERL: new Pokemon(366),
  HUNTAIL: new Pokemon(367),
  GOREBYSS: new Pokemon(368),
  RELICANTH: new Pokemon(369),
  LUVDISC: new Pokemon(370),
  BAGON: new Pokemon(371),
  SHELGON: new Pokemon(372),
  SALAMENCE: new Pokemon(373),
  BELDUM: new Pokemon(374),
  METANG: new Pokemon(375),
  METAGROSS: new Pokemon(376),
  REGIROCK: new Pokemon(377),
  REGICE: new Pokemon(378),
  REGISTEEL: new Pokemon(379),
  LATIAS: new Pokemon(380),
  LATIOS: new Pokemon(381),
  KYOGRE: new Pokemon(382),
  GROUDON: new Pokemon(383),
  RAYQUAZA: new Pokemon(384),
  JIRACHI: new Pokemon(385),
  DEOXYS: new Pokemon(386).withForms('NORMAL', 'ATTACK', 'DEFENSE', 'SPEED'),
  TURTWIG: new Pokemon(387),
  GROTLE: new Pokemon(388),
  TORTERRA: new Pokemon(389),
  CHIMCHAR: new Pokemon(390),
  MONFERNO: new Pokemon(391),
  INFERNAPE: new Pokemon(392),
  PIPLUP: new Pokemon(393),
  PRINPLUP: new Pokemon(394),
  EMPOLEON: new Pokemon(395),
  STARLY: new Pokemon(396),
  STARAVIA: new Pokemon(397),
  STARAPTOR: new Pokemon(398),
  BIDOOF: new Pokemon(399),
  BIBAREL: new Pokemon(400),
  KRICKETOT: new Pokemon(401),
  KRICKETUNE: new Pokemon(402),
  SHINX: new Pokemon(403),
  LUXIO: new Pokemon(404),
  LUXRAY: new Pokemon(405),
  BUDEW: new Pokemon(406),
  ROSERADE: new Pokemon(407),
  CRANIDOS: new Pokemon(408),
  RAMPARDOS: new Pokemon(409),
  SHIELDON: new Pokemon(410),
  BASTIODON: new Pokemon(411),
  BURMY: new Pokemon(412).withForms('PLANT_CLOAK', 'SANDY_CLOAK', 'TRASH_CLOAK'),
  WORMADAM: new Pokemon(413).withForms('PLANT_CLOAK', 'SANDY_CLOAK', 'TRASH_CLOAK'),
  MOTHIM: new Pokemon(414),
  COMBEE: new Pokemon(415),
  VESPIQUEN: new Pokemon(416),
  PACHIRISU: new Pokemon(417),
  BUIZEL: new Pokemon(418),
  FLOATZEL: new Pokemon(419),
  CHERUBI: new Pokemon(420),
  CHERRIM: new Pokemon(421).withForms('OVERCAST', 'SUNNY'),
  SHELLOS: new Pokemon(422),
  GASTRODON: new Pokemon(423),
  AMBIPOM: new Pokemon(424),
  DRIFLOON: new Pokemon(425),
  DRIFBLIM: new Pokemon(426),
  BUNEARY: new Pokemon(427),
  LOPUNNY: new Pokemon(428),
  MISMAGIUS: new Pokemon(429),
  HONCHKROW: new Pokemon(430),
  GLAMEOW: new Pokemon(431),
  PURUGLY: new Pokemon(432),
  CHINGLING: new Pokemon(433),
  STUNKY: new Pokemon(434),
  SKUNTANK: new Pokemon(435),
  BRONZOR: new Pokemon(436),
  BRONZONG: new Pokemon(437),
  BONSLY: new Pokemon(438),
  MIME_JR: new Pokemon(439),
  HAPPINY: new Pokemon(440),
  CHATOT: new Pokemon(441),
  SPIRITOMB: new Pokemon(442),
  GIBLE: new Pokemon(443),
  GABITE: new Pokemon(444),
  GARCHOMP: new Pokemon(445),
  MUNCHLAX: new Pokemon(446),
  RIOLU: new Pokemon(447),
  LUCARIO: new Pokemon(448),
  HIPPOPOTAS: new Pokemon(449),
  HIPPOWDON: new Pokemon(450),
  SKORUPI: new Pokemon(451),
  DRAPION: new Pokemon(452),
  CROAGUNK: new Pokemon(453),
  TOXICROAK: new Pokemon(454),
  CARNIVINE: new Pokemon(455),
  FINNEON: new Pokemon(456),
  LUMINEON: new Pokemon(457),
  MANTYKE: new Pokemon(458),
  SNOVER: new Pokemon(459),
  ABOMASNOW: new Pokemon(460),
  WEAVILE: new Pokemon(461),
  MAGNEZONE: new Pokemon(462),
  LICKILICKY: new Pokemon(463),
  RHYPERIOR: new Pokemon(464),
  TANGROWTH: new Pokemon(465),
  ELECTIVIRE: new Pokemon(466),
  MAGMORTAR: new Pokemon(467),
  TOGEKISS: new Pokemon(468),
  YANMEGA: new Pokemon(469),
  LEAFEON: new Pokemon(470),
  GLACEON: new Pokemon(471),
  GLISCOR: new Pokemon(472),
  MAMOSWINE: new Pokemon(473),
  PORYGON_Z: new Pokemon(474),
  GALLADE: new Pokemon(475),
  PROBOPASS: new Pokemon(476),
  DUSKNOIR: new Pokemon(477),
  FROSLASS: new Pokemon(478),
  ROTOM: new Pokemon(479).withForms('NORMAL', 'HEAT', 'WASH', 'FROST', 'FAN', 'MOW'),
  UXIE: new Pokemon(480),
  MESPRIT: new Pokemon(481),
  AZELF: new Pokemon(482),
  DIALGA: new Pokemon(483),
  PALKIA: new Pokemon(484),
  HEATRAN: new Pokemon(485),
  REGIGIGAS: new Pokemon(486),
  GIRATINA: new Pokemon(487),
  CRESSELIA: new Pokemon(488),
  PHIONE: new Pokemon(489),
  MANAPHY: new Pokemon(490),
  DARKRAI: new Pokemon(491),
  SHAYMIN: new Pokemon(492).withForms('LAND_FORME', 'SKY_FORME'),
  ARCEUS: new Pokemon(493),
  VICTINI: new Pokemon(494),
  SNIVY: new Pokemon(495),
  SERVINE: new Pokemon(496),
  SERPERIOR: new Pokemon(497),
  TEPIG: new Pokemon(498),
  PIGNITE: new Pokemon(499),
  EMBOAR: new Pokemon(500),
  OSHAWOTT: new Pokemon(501),
  DEWOTT: new Pokemon(502),
  SAMUROTT: new Pokemon(503).withRegions(HISUI),
  PATRAT: new Pokemon(504),
  WATCHOG: new Pokemon(505),
  LILLIPUP: new Pokemon(506),
  HERDIER: new Pokemon(507),
  STOUTLAND: new Pokemon(508),
  PURRLOIN: new Pokemon(509),
  LIEPARD: new Pokemon(510),
  PANSAGE: new Pokemon(511),
  SIMISAGE: new Pokemon(512),
  PANSEAR: new Pokemon(513),
  SIMISEAR: new Pokemon(514),
  PANPOUR: new Pokemon(515),
  SIMIPOUR: new Pokemon(516),
  MUNNA: new Pokemon(517),
  MUSHARNA: new Pokemon(518),
  PIDOVE: new Pokemon(519),
  TRANQUILL: new Pokemon(520),
  UNFEZANT: new Pokemon(521),
  BLITZLE: new Pokemon(522),
  ZEBSTRIKA: new Pokemon(523),
  ROGGENROLA: new Pokemon(524),
  BOLDORE: new Pokemon(525),
  GIGALITH: new Pokemon(526),
  WOOBAT: new Pokemon(527),
  SWOOBAT: new Pokemon(528),
  DRILBUR: new Pokemon(529),
  EXCADRILL: new Pokemon(530),
  AUDINO: new Pokemon(531),
  TIMBURR: new Pokemon(532),
  GURDURR: new Pokemon(533),
  CONKELDURR: new Pokemon(534),
  TYMPOLE: new Pokemon(535),
  PALPITOAD: new Pokemon(536),
  SEISMITOAD: new Pokemon(537),
  THROH: new Pokemon(538),
  SAWK: new Pokemon(539),
  SEWADDLE: new Pokemon(540),
  SWADLOON: new Pokemon(541),
  LEAVANNY: new Pokemon(542),
  VENIPEDE: new Pokemon(543),
  WHIRLIPEDE: new Pokemon(544),
  SCOLIPEDE: new Pokemon(545),
  COTTONEE: new Pokemon(546),
  WHIMSICOTT: new Pokemon(547),
  PETILIL: new Pokemon(548),
  LILLIGANT: new Pokemon(549).withRegions(HISUI),
  BASCULIN: new Pokemon(550).withForms('RED_STRIPED', 'BLUE_STRIPED', 'WHITE_STRIPED'),
  SANDILE: new Pokemon(551),
  KROKOROK: new Pokemon(552),
  KROOKODILE: new Pokemon(553),
  DARUMAKA: new Pokemon(554).withRegions(GALAR),
  DARMANITAN: new Pokemon(555).withRegions(GALAR).withForms('STANDARD_MODE', 'ZEN_MODE'),
  MARACTUS: new Pokemon(556),
  DWEBBLE: new Pokemon(557),
  CRUSTLE: new Pokemon(558),
  SCRAGGY: new Pokemon(559),
  SCRAFTY: new Pokemon(560),
  SIGILYPH: new Pokemon(561),
  YAMASK: new Pokemon(562).withRegions(GALAR),
  COFAGRIGUS: new Pokemon(563),
  TIRTOUGA: new Pokemon(564),
  CARRACOSTA: new Pokemon(565),
  ARCHEN: new Pokemon(566),
  ARCHEOPS: new Pokemon(567),
  TRUBBISH: new Pokemon(568),
  GARBODOR: new Pokemon(569),
  ZORUA: new Pokemon(570).withRegions(HISUI),
  ZOROARK: new Pokemon(571).withRegions(HISUI),
  MINCCINO: new Pokemon(572),
  CINCCINO: new Pokemon(573),
  GOTHITA: new Pokemon(574),
  GOTHORITA: new Pokemon(575),
  GOTHITELLE: new Pokemon(576),
  SOLOSIS: new Pokemon(577),
  DUOSION: new Pokemon(578),
  REUNICLUS: new Pokemon(579),
  DUCKLETT: new Pokemon(580),
  SWANNA: new Pokemon(581),
  VANILLITE: new Pokemon(582),
  VANILLISH: new Pokemon(583),
  VANILLUXE: new Pokemon(584),
  DEERLING: new Pokemon(585).withForms('SPRING_FORM', 'SUMMER_FORM', 'AUTUMN_FORM', 'WINTER_FORM'),
  SAWSBUCK: new Pokemon(586).withForms('SPRING_FORM', 'SUMMER_FORM', 'AUTUMN_FORM', 'WINTER_FORM'),
  EMOLGA: new Pokemon(587),
  KARRABLAST: new Pokemon(588),
  ESCAVALIER: new Pokemon(589),
  FOONGUS: new Pokemon(590),
  AMOONGUSS: new Pokemon(591),
  FRILLISH: new Pokemon(592).withForms('MALE', 'FEMALE'),
  JELLICENT: new Pokemon(593).withForms('MALE', 'FEMALE'),
  ALOMOMOLA: new Pokemon(594),
  JOLTIK: new Pokemon(595),
  GALVANTULA: new Pokemon(596),
  FERROSEED: new Pokemon(597),
  FERROTHORN: new Pokemon(598),
  KLINK: new Pokemon(599),
  KLANG: new Pokemon(600),
  KLINKLANG: new Pokemon(601),
  TYNAMO: new Pokemon(602),
  EELEKTRIK: new Pokemon(603),
  EELEKTROSS: new Pokemon(604),
  ELGYEM: new Pokemon(605),
  BEHEEYEM: new Pokemon(606),
  LITWICK: new Pokemon(607),
  LAMPENT: new Pokemon(608),
  CHANDELURE: new Pokemon(609),
  AXEW: new Pokemon(610),
  FRAXURE: new Pokemon(611),
  HAXORUS: new Pokemon(612),
  CUBCHOO: new Pokemon(613),
  BEARTIC: new Pokemon(614),
  CRYOGONAL: new Pokemon(615),
  SHELMET: new Pokemon(616),
  ACCELGOR: new Pokemon(617),
  STUNFISK: new Pokemon(618).withRegions(GALAR),
  MIENFOO: new Pokemon(619),
  MIENSHAO: new Pokemon(620),
  DRUDDIGON: new Pokemon(621),
  GOLETT: new Pokemon(622),
  GOLURK: new Pokemon(623),
  PAWNIARD: new Pokemon(624),
  BISHARP: new Pokemon(625),
  BOUFFALANT: new Pokemon(626),
  RUFFLET: new Pokemon(627),
  BRAVIARY: new Pokemon(628).withRegions(HISUI),
  VULLABY: new Pokemon(629),
  MANDIBUZZ: new Pokemon(630),
  HEATMOR: new Pokemon(631),
  DURANT: new Pokemon(632),
  DEINO: new Pokemon(633),
  ZWEILOUS: new Pokemon(634),
  HYDREIGON: new Pokemon(635),
  LARVESTA: new Pokemon(636),
  VOLCARONA: new Pokemon(637),
  COBALION: new Pokemon(638),
  TERRAKION: new Pokemon(639),
  VIRIZION: new Pokemon(640),
  TORNADUS: new Pokemon(641).withForms('INCARNATE_FORME', 'THERIAN_FORME'),
  THUNDURUS: new Pokemon(642).withForms('INCARNATE_FORME', 'THERIAN_FORME'),
  RESHIRAM: new Pokemon(643),
  ZEKROM: new Pokemon(644),
  LANDORUS: new Pokemon(645).withForms('INCARNATE_FORME', 'THERIAN_FORME'),
  KYUREM: new Pokemon(646).withForms('NORMAL', 'BLACK', 'WHITE'),
  KELDEO: new Pokemon(647).withForms('ORDINARY_FORM', 'RESOLUTE_FORM'),
  MELOETTA: new Pokemon(648),
  GENESECT: new Pokemon(649).withForms('NORMAL', 'DOUSE_DRIVE', 'SHOCK_DRIVE', 'BURN_DRIVE', 'CHILL_DRIVE'),
  CHESPIN: new Pokemon(650),
  QUILLADIN: new Pokemon(651),
  CHESNAUGHT: new Pokemon(652),
  FENNEKIN: new Pokemon(653),
  BRAIXEN: new Pokemon(654),
  DELPHOX: new Pokemon(655),
  FROAKIE: new Pokemon(656),
  FROGADIER: new Pokemon(657),
  GRENINJA: new Pokemon(658),
  BUNNELBY: new Pokemon(659),
  DIGGERSBY: new Pokemon(660),
  FLETCHLING: new Pokemon(661),
  FLETCHINDER: new Pokemon(662),
  TALONFLAME: new Pokemon(663),
  SCATTERBUG: new Pokemon(664),
  SPEWPA: new Pokemon(665),
  VIVILLON: new Pokemon(666).withForms(
    'ICY_SNOW',
    'POLAR',
    'TUNDRA',
    'CONTINENTAL',
    'GARDEN',
    'ELEGANT',
    'MEADOW',
    'MODERN',
    'MARINE',
    'ARCHIPELAGO',
    'HIGH_PLAINS',
    'SANDSTORM',
    'RIVER',
    'MONSOON',
    'SAVANNA',
    'SUN',
    'OCEAN',
    'JUNGLE',
    'FANCY',
    'POKE_BALL',
  ),
  LITLEO: new Pokemon(667),
  PYROAR: new Pokemon(668).withForms('MALE', 'FEMALE'),
  FLABEBE: new Pokemon(669).withForms('RED_FLOWER', 'YELLOW_FLOWER', 'ORANGE_FLOWER', 'BLUE_FLOWER', 'WHITE_FLOWER'),
  FLOETTE: new Pokemon(670).withForms(
    'RED_FLOWER',
    'YELLOW_FLOWER',
    'ORANGE_FLOWER',
    'BLUE_FLOWER',
    'WHITE_FLOWER',
    'ETERNAL_FLOWER',
  ),
  FLORGES: new Pokemon(671).withForms('RED_FLOWER', 'YELLOW_FLOWER', 'ORANGE_FLOWER', 'BLUE_FLOWER', 'WHITE_FLOWER'),
  SKIDDO: new Pokemon(672),
  GOGOAT: new Pokemon(673),
  PANCHAM: new Pokemon(674),
  PANGORO: new Pokemon(675),
  FURFROU: new Pokemon(676).withForms(
    'NATURAL_FORM',
    'HEART_TRIM',
    'STAR_TRIM',
    'DIAMOND_TRIM',
    'DEBUTANTE_TRIM',
    'MATRON_TRIM',
    'DANDY_TRIM',
    'LA_REINE_TRIM',
    'KABUKI_TRIM',
    'PHARAOH_TRIM',
  ),
  ESPURR: new Pokemon(677),
  MEOWSTIC: new Pokemon(678).withForms('MALE', 'FEMALE'),
  HONEDGE: new Pokemon(679),
  DOUBLADE: new Pokemon(680),
  AEGISLASH: new Pokemon(681).withForms('SHIELD_FORME', 'BLADE_FORME'),
  SPRITZEE: new Pokemon(682),
  AROMATISSE: new Pokemon(683),
  SWIRLIX: new Pokemon(684),
  SLURPUFF: new Pokemon(685),
  INKAY: new Pokemon(686),
  MALAMAR: new Pokemon(687),
  BINACLE: new Pokemon(688),
  BARBARACLE: new Pokemon(689),
  SKRELP: new Pokemon(690),
  DRAGALGE: new Pokemon(691),
  CLAUNCHER: new Pokemon(692),
  CLAWITZER: new Pokemon(693),
  HELIOPTILE: new Pokemon(694),
  HELIOLISK: new Pokemon(695),
  TYRUNT: new Pokemon(696),
  TYRANTRUM: new Pokemon(697),
  AMAURA: new Pokemon(698),
  AURORUS: new Pokemon(699),
  SYLVEON: new Pokemon(700),
  HAWLUCHA: new Pokemon(701),
  DEDENNE: new Pokemon(702),
  CARBINK: new Pokemon(703),
  GOOMY: new Pokemon(704),
  SLIGGOO: new Pokemon(705).withRegions(HISUI),
  GOODRA: new Pokemon(706).withRegions(HISUI),
  KLEFKI: new Pokemon(707),
  PHANTUMP: new Pokemon(708),
  TREVENANT: new Pokemon(709),
  PUMPKABOO: new Pokemon(710).withForms('AVERAGE_SIZE', 'SMALL_SIZE', 'LARGE_SIZE', 'SUPER_SIZE'),
  GOURGEIST: new Pokemon(711).withForms('AVERAGE_SIZE', 'SMALL_SIZE', 'LARGE_SIZE', 'SUPER_SIZE'),
  BERGMITE: new Pokemon(712),
  AVALUGG: new Pokemon(713).withRegions(HISUI),
  NOIBAT: new Pokemon(714),
  NOIVERN: new Pokemon(715),
  XERNEAS: new Pokemon(716),
  YVELTAL: new Pokemon(717),
  ZYGARDE: new Pokemon(718).withForms('FIFTY_PERCENT_FORME', 'TEN_PERCENT_FORME', 'COMPLETE_FORME'),
  DIANCIE: new Pokemon(719),
  HOOPA: new Pokemon(720).withForms('CONFINED', 'UNBOUND'),
  VOLCANION: new Pokemon(721),
  ROWLET: new Pokemon(722),
  DARTRIX: new Pokemon(723),
  DECIDUEYE: new Pokemon(724).withRegions(HISUI),
  LITTEN: new Pokemon(725),
  TORRACAT: new Pokemon(726),
  INCINEROAR: new Pokemon(727),
  POPPLIO: new Pokemon(728),
  BRIONNE: new Pokemon(729),
  PRIMARINA: new Pokemon(730),
  PIKIPEK: new Pokemon(731),
  TRUMBEAK: new Pokemon(732),
  TOUCANNON: new Pokemon(733),
  YUNGOOS: new Pokemon(734),
  GUMSHOOS: new Pokemon(735),
  GRUBBIN: new Pokemon(736),
  CHARJABUG: new Pokemon(737),
  VIKAVOLT: new Pokemon(738),
  CRABRAWLER: new Pokemon(739),
  CRABOMINABLE: new Pokemon(740),
  ORICORIO: new Pokemon(741).withForms('BAILE_STYLE', 'POM_POM_STYLE', 'PAU_STYLE', 'SENSU_STYLE'),
  CUTIEFLY: new Pokemon(742),
  RIBOMBEE: new Pokemon(743),
  ROCKRUFF: new Pokemon(744),
  LYCANROC: new Pokemon(745).withForms('MIDDAY_FORM', 'MIDNIGHT_FORM', 'DUSK_FORM'),
  WISHIWASHI: new Pokemon(746).withForms('SOLO_FORM', 'SCHOOL_FORM'),
  MAREANIE: new Pokemon(747),
  TOXAPEX: new Pokemon(748),
  MUDBRAY: new Pokemon(749),
  MUDSDALE: new Pokemon(750),
  DEWPIDER: new Pokemon(751),
  ARAQUANID: new Pokemon(752),
  FOMANTIS: new Pokemon(753),
  LURANTIS: new Pokemon(754),
  MORELULL: new Pokemon(755),
  SHIINOTIC: new Pokemon(756),
  SALANDIT: new Pokemon(757),
  SALAZZLE: new Pokemon(758),
  STUFFUL: new Pokemon(759),
  BEWEAR: new Pokemon(760),
  BOUNSWEET: new Pokemon(761),
  STEENEE: new Pokemon(762),
  TSAREENA: new Pokemon(763),
  COMFEY: new Pokemon(764),
  ORANGURU: new Pokemon(765),
  PASSIMIAN: new Pokemon(766),
  WIMPOD: new Pokemon(767),
  GOLISOPOD: new Pokemon(768),
  SANDYGAST: new Pokemon(769),
  PALOSSAND: new Pokemon(770),
  PYUKUMUKU: new Pokemon(771),
  TYPE_NULL: new Pokemon(772),
  SILVALLY: new Pokemon(773),
  MINIOR: new Pokemon(774),
  KOMALA: new Pokemon(775),
  TURTONATOR: new Pokemon(776),
  TOGEDEMARU: new Pokemon(777),
  MIMIKYU: new Pokemon(778).withForms('DISGUISED_FORM', 'BUSTED_FORM'),
  BRUXISH: new Pokemon(779),
  DRAMPA: new Pokemon(780),
  DHELMISE: new Pokemon(781),
  JANGMO_O: new Pokemon(782),
  HAKAMO_O: new Pokemon(783),
  KOMMO_O: new Pokemon(784),
  TAPU_KOKO: new Pokemon(785),
  TAPU_LELE: new Pokemon(786),
  TAPU_BULU: new Pokemon(787),
  TAPU_FINI: new Pokemon(788),
  COSMOG: new Pokemon(789),
  COSMOEM: new Pokemon(790),
  SOLGALEO: new Pokemon(791),
  LUNALA: new Pokemon(792),
  NIHILEGO: new Pokemon(793),
  BUZZWOLE: new Pokemon(794),
  PHEROMOSA: new Pokemon(795),
  XURKITREE: new Pokemon(796),
  CELESTEELA: new Pokemon(797),
  KARTANA: new Pokemon(798),
  GUZZLORD: new Pokemon(799),
  NECROZMA: new Pokemon(800).withForms('NORMAL', 'DUSK_MANE', 'DAWN_WINGS', 'ULTRA'),
  MAGEARNA: new Pokemon(801),
  MARSHADOW: new Pokemon(802),
  POIPOLE: new Pokemon(803),
  NAGANADEL: new Pokemon(804),
  STAKATAKA: new Pokemon(805),
  BLACEPHALON: new Pokemon(806),
  ZERAORA: new Pokemon(807),
  MELTAN: new Pokemon(808),
  MELMETAL: new Pokemon(809),
  GROOKEY: new Pokemon(810),
  THWACKEY: new Pokemon(811),
  RILLABOOM: new Pokemon(812),
  SCORBUNNY: new Pokemon(813),
  RABOOT: new Pokemon(814),
  CINDERACE: new Pokemon(815),
  SOBBLE: new Pokemon(816),
  DRIZZILE: new Pokemon(817),
  INTELEON: new Pokemon(818),
  SKWOVET: new Pokemon(819),
  GREEDENT: new Pokemon(820),
  ROOKIDEE: new Pokemon(821),
  CORVISQUIRE: new Pokemon(822),
  CORVIKNIGHT: new Pokemon(823),
  BLIPBUG: new Pokemon(824),
  DOTTLER: new Pokemon(825),
  ORBEETLE: new Pokemon(826),
  NICKIT: new Pokemon(827),
  THIEVUL: new Pokemon(828),
  GOSSIFLEUR: new Pokemon(829),
  ELDEGOSS: new Pokemon(830),
  WOOLOO: new Pokemon(831),
  DUBWOOL: new Pokemon(832),
  CHEWTLE: new Pokemon(833),
  DREDNAW: new Pokemon(834),
  YAMPER: new Pokemon(835),
  BOLTUND: new Pokemon(836),
  ROLYCOLY: new Pokemon(837),
  CARKOL: new Pokemon(838),
  COALOSSAL: new Pokemon(839),
  APPLIN: new Pokemon(840),
  FLAPPLE: new Pokemon(841),
  APPLETUN: new Pokemon(842),
  SILICOBRA: new Pokemon(843),
  SANDACONDA: new Pokemon(844),
  CRAMORANT: new Pokemon(845),
  ARROKUDA: new Pokemon(846),
  BARRASKEWDA: new Pokemon(847),
  TOXEL: new Pokemon(848),
  TOXTRICITY: new Pokemon(849).withForms('AMPED_FORM', 'LOW_KEY_FORM'),
  SIZZLIPEDE: new Pokemon(850),
  CENTISKORCH: new Pokemon(851),
  CLOBBOPUS: new Pokemon(852),
  GRAPPLOCT: new Pokemon(853),
  SINISTEA: new Pokemon(854).withForms('PHONY_FORM', 'ANTIQUE_FORM'),
  POLTEAGEIST: new Pokemon(855).withForms('PHONY_FORM', 'ANTIQUE_FORM'),
  HATENNA: new Pokemon(856),
  HATTREM: new Pokemon(857),
  HATTERENE: new Pokemon(858),
  IMPIDIMP: new Pokemon(859),
  MORGREM: new Pokemon(860),
  GRIMMSNARL: new Pokemon(861),
  OBSTAGOON: new Pokemon(862),
  PERRSERKER: new Pokemon(863),
  CURSOLA: new Pokemon(864),
  SIRFETCHD: new Pokemon(865),
  MR_RIME: new Pokemon(866),
  RUNERIGUS: new Pokemon(867),
  MILCERY: new Pokemon(868),
  ALCREMIE: new Pokemon(869),
  FALINKS: new Pokemon(870),
  PINCURCHIN: new Pokemon(871),
  SNOM: new Pokemon(872),
  FROSMOTH: new Pokemon(873),
  STONJOURNER: new Pokemon(874),
  EISCUE: new Pokemon(875),
  INDEEDEE: new Pokemon(876),
  MORPEKO: new Pokemon(877).withForms('FULL_BELLY_MODE', 'HANGRY_MODE'),
  CUFANT: new Pokemon(878),
  COPPERAJAH: new Pokemon(879),
  DRACOZOLT: new Pokemon(880),
  ARCTOZOLT: new Pokemon(881),
  DRACOVISH: new Pokemon(882),
  ARCTOVISH: new Pokemon(883),
  DURALUDON: new Pokemon(884),
  DREEPY: new Pokemon(885),
  DRAKLOAK: new Pokemon(886),
  DRAGAPULT: new Pokemon(887),
  ZACIAN: new Pokemon(888).withForms('HERO_OF_MANY_BATTLES', 'CROWNED_SWORD'),
  ZAMAZENTA: new Pokemon(889).withForms('HERO_OF_MANY_BATTLES', 'CROWNED_SHIELD'),
  ETERNATUS: new Pokemon(890).withForms('NORMAL', 'ETERNAMAX'),
  KUBFU: new Pokemon(891),
  URSHIFU: new Pokemon(892).withForms('SINGLE_STRIKE_STYLE', 'RAPID_STRIKE_STYLE'),
  ZARUDE: new Pokemon(893),
  REGIELEKI: new Pokemon(894),
  REGIDRAGO: new Pokemon(895),
  GLASTRIER: new Pokemon(896),
  SPECTRIER: new Pokemon(897),
  CALYREX: new Pokemon(898),
  WYRDEER: new Pokemon(899),
  KLEAVOR: new Pokemon(900),
  URSALUNA: new Pokemon(901),
  BASCULEGION: new Pokemon(902),
  SNEASLER: new Pokemon(903),
  OVERQWIL: new Pokemon(904),
  ENAMORUS: new Pokemon(905).withForms('INCARNATE_FORME', 'THERIAN_FORME'),
  SPRIGATITO: new Pokemon(906),
  FLORAGATO: new Pokemon(907),
  MEOWSCARADA: new Pokemon(908),
  FUECOCO: new Pokemon(909),
  CROCALOR: new Pokemon(910),
  SKELEDIRGE: new Pokemon(911),
  QUAXLY: new Pokemon(912),
  QUAXWELL: new Pokemon(913),
  QUAQUAVAL: new Pokemon(914),
  LECHONK: new Pokemon(915),
  OINKOLOGNE: new Pokemon(916).withForms('MALE', 'FEMALE'),
  TAROUNTULA: new Pokemon(917),
  SPIDOPS: new Pokemon(918),
  NYMBLE: new Pokemon(919),
  LOKIX: new Pokemon(920),
  PAWMI: new Pokemon(921),
  PAWMO: new Pokemon(922),
  PAWMOT: new Pokemon(923),
  TANDEMAUS: new Pokemon(924),
  MAUSHOLD: new Pokemon(925).withForms('FAMILY_OF_THREE', 'FAMILY_OF_FOUR'),
  FIDOUGH: new Pokemon(926),
  DACHSBUN: new Pokemon(927),
  SMOLIV: new Pokemon(928),
  DOLLIV: new Pokemon(929),
  ARBOLIVA: new Pokemon(930),
  SQUAWKABILLY: new Pokemon(931).withForms('GREEN_PLUMAGE', 'BLUE_PLUMAGE', 'YELLOW_PLUMAGE', 'WHITE_PLUMAGE'),
  NACLI: new Pokemon(932),
  NACLSTACK: new Pokemon(933),
  GARGANACL: new Pokemon(934),
  CHARCADET: new Pokemon(935),
  ARMAROUGE: new Pokemon(936),
  CERULEDGE: new Pokemon(937),
  TADBULB: new Pokemon(938),
  BELLIBOLT: new Pokemon(939),
  WATTREL: new Pokemon(940),
  KILOWATTREL: new Pokemon(941),
  MASCHIFF: new Pokemon(942),
  MABOSSTIFF: new Pokemon(943),
  SHROODLE: new Pokemon(944),
  GRAFAIAI: new Pokemon(945),
  BRAMBLIN: new Pokemon(946),
  BRAMBLEGHAST: new Pokemon(947),
  TOEDSCOOL: new Pokemon(948),
  TOEDSCRUEL: new Pokemon(949),
  KLAWF: new Pokemon(950),
  CAPSAKID: new Pokemon(951),
  SCOVILLAIN: new Pokemon(952),
  RELLOR: new Pokemon(953),
  RABSCA: new Pokemon(954),
  FLITTLE: new Pokemon(955),
  ESPATHRA: new Pokemon(956),
  TINKATINK: new Pokemon(957),
  TINKATUFF: new Pokemon(958),
  TINKATON: new Pokemon(959),
  WIGLETT: new Pokemon(960),
  WUGTRIO: new Pokemon(961),
  BOMBIRDIER: new Pokemon(962),
  FINIZEN: new Pokemon(963),
  PALAFIN: new Pokemon(964),
  VAROOM: new Pokemon(965),
  REVAVROOM: new Pokemon(966),
  CYCLIZAR: new Pokemon(967),
  ORTHWORM: new Pokemon(968),
  GLIMMET: new Pokemon(969),
  GLIMMORA: new Pokemon(970),
  GREAVARD: new Pokemon(971),
  HOUNDSTONE: new Pokemon(972),
  FLAMIGO: new Pokemon(973),
  CETODDLE: new Pokemon(974),
  CETITAN: new Pokemon(975),
  VELUZA: new Pokemon(976),
  DONDOZO: new Pokemon(977),
  TATSUGIRI: new Pokemon(978).withForms('CURLY_FORM', 'DROOPY_FORM', 'STRETCHY_FORM'),
  ANNIHILAPE: new Pokemon(979),
  CLODSIRE: new Pokemon(980),
  FARIGIRAF: new Pokemon(981),
  DUDUNSPARCE: new Pokemon(982).withForms('TWO_SEGMENT_FORM', 'THREE_SEGMENT_FORM'),
  KINGAMBIT: new Pokemon(983),
  GREAT_TUSK: new Pokemon(984),
  SCREAM_TAIL: new Pokemon(985),
  BRUTE_BONNET: new Pokemon(986),
  FLUTTER_MANE: new Pokemon(987),
  SLITHER_WING: new Pokemon(988),
  SANDY_SHOCKS: new Pokemon(989),
  IRON_TREADS: new Pokemon(990),
  IRON_BUNDLE: new Pokemon(991),
  IRON_HANDS: new Pokemon(992),
  IRON_JUGULIS: new Pokemon(993),
  IRON_MOTH: new Pokemon(994),
  IRON_THORNS: new Pokemon(995),
  FRIGIBAX: new Pokemon(996),
  ARCTIBAX: new Pokemon(997),
  BAXCALIBUR: new Pokemon(998),
  GIMMIGHOUL: new Pokemon(999).withForms('CHEST_FORM', 'ROAMING_FORM'),
  GHOLDENGO: new Pokemon(1000),
  WO_CHIEN: new Pokemon(1001),
  CHIEN_PAO: new Pokemon(1002),
  TING_LU: new Pokemon(1003),
  CHI_YU: new Pokemon(1004),
  ROARING_MOON: new Pokemon(1005),
  IRON_VALIANT: new Pokemon(1006),
  KORAIDON: new Pokemon(1007),
  MIRAIDON: new Pokemon(1008),
  WALKING_WAKE: new Pokemon(1009),
  IRON_LEAVES: new Pokemon(1010),
  DIPPLIN: new Pokemon(1011),
  POLTCHAGEIST: new Pokemon(1012).withForms('COUNTERFEIT_FORM', 'ARTISAN_FORM'),
  SINISTCHA: new Pokemon(1013).withForms('UNREMARKABLE_FORM', 'MASTERPIECE_FORM'),
  OKIDOGI: new Pokemon(1014),
  MUNKIDORI: new Pokemon(1015),
  FEZANDIPITI: new Pokemon(1016),
  OGERPON: new Pokemon(1017),
  ARCHALUDON: new Pokemon(1018),
  HYDRAPPLE: new Pokemon(1019),
  GOUGING_FIRE: new Pokemon(1020),
  RAGING_BOLT: new Pokemon(1021),
  IRON_BOULDER: new Pokemon(1022),
  IRON_CROWN: new Pokemon(1023),
  TERAPAGOS: new Pokemon(1024).withForms('NORMAL_FORM', 'TERASTAL_FORM', 'STELLAR_FORM'),
  PECHARUNT: new Pokemon(1025),
};

// Each species answers to the constant it is bound to, so an error names the species rather than its number.
for (const [name, species] of Object.entries(POKEMON)) {
  species.as(name);
}

export default POKEMON;
