---
name: "Lint"

on:
  push:
    branches: ["master"]
  pull_request: {}

permissions:
  contents: "read"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - uses: "pnpm/setup@v2"
        with:
          cache: true

      - name: "JavaScript"
        run: "pnpm lint:js"

      - name: "CSS"
        if: ${{ !cancelled() }}
        run: "pnpm lint:css"

      - name: "HTML"
        if: ${{ !cancelled() }}
        run: "pnpm lint:html"

      - name: "XML"
        if: ${{ !cancelled() }}
        run: "pnpm lint:xml"

      - name: "Prettier"
        if: ${{ !cancelled() }}
        run: "pnpm lint:prettier"
